### ISSUE TITLE
ceph-container support for LVM multiple OSDs?

### ISSUE THREAD

**Issue by jdeglopper** [ceph/ceph-container#1038]
Hi - I'm trying to set up our first Ceph deployment with a small set of 3 servers, using an SSD boot drive each and 2x Micron 5200 SSDs per server for OSD drives.  It appears that Ceph under Docker gives us an allowable production config using 3 servers rather than 6.  We are using CentOS 7.4 as the host operating system.

I was able to get the cluster up and running using ceph-ansible with one OSD per drive, using Bluestore, but 4k block and MySQL performance was below the performance of a single SSD.  One possible tuning step appears to be running 4-6 OSDs per SSD rather than 1, but I'm having trouble getting ceph-ansible to provision that.  My impression is that I should preconfigure LVM volumes for the OSDs, and I've done that (this is a test on a clean VM install to eliminate any leftovers from my previous cluster):
`
  osda1 vg3    -wi-a----- 13.50g
  osda2 vg3    -wi-a----- 13.50g
  osda3 vg3    -wi-a----- 13.50g
  osda4 vg3    -wi-a----- 13.50g 
`
I'm trying to get these OSDs up and running; it's unclear if ceph-ansible has support for the LVM scenario or not, but I'm also having trouble doing it manually:
`
docker run  --net=host --name ceph-osda2 --privileged=true --pid=host  -v /dev/:/dev/ -v /sys/block/:/sys/block/  -v /etc/localtime:/etc/localtime:ro  -v /var/lib/ceph:/var/lib/ceph -v /etc/ceph:/etc/ceph -e OSD_DEVICE=/dev/mapper/vg3-osda2 docker.io/ceph/daemon:latest osd_ceph_disk_prepare
`
This eventually dies at:
`get_dm_uuid: get_dm_uuid /dev/mapper/vg3-osda2 uuid path is /sys/dev/block/253:3/dm/uuid
get_dm_uuid: get_dm_uuid /dev/mapper/vg3-osda2 uuid is LVM-7sdIDlcVKpAERiXcU7aq0zBimsyIidb2WmLXr5Fzg9QUAF58elI3xAOvQf2tKfiw

Traceback (most recent call last):
  File "/usr/sbin/ceph-disk", line 9, in <module>
    load_entry_point('ceph-disk==1.0.0', 'console_scripts', 'ceph-disk')()
  File "/usr/lib/python2.7/site-packages/ceph_disk/main.py", line 5735, in run
    main(sys.argv[1:])
  File "/usr/lib/python2.7/site-packages/ceph_disk/main.py", line 5686, in main
    args.func(args)
  File "/usr/lib/python2.7/site-packages/ceph_disk/main.py", line 2107, in main
    Prepare.factory(args).prepare()
  File "/usr/lib/python2.7/site-packages/ceph_disk/main.py", line 2096, in prepare
    self._prepare()
  File "/usr/lib/python2.7/site-packages/ceph_disk/main.py", line 2177, in _prepare
    self.data.prepare(*to_prepare_list)
  File "/usr/lib/python2.7/site-packages/ceph_disk/main.py", line 2951, in prepare
    self.prepare_device(*to_prepare_list)
  File "/usr/lib/python2.7/site-packages/ceph_disk/main.py", line 3126, in prepare_device
    self.set_data_partition()
  File "/usr/lib/python2.7/site-packages/ceph_disk/main.py", line 3041, in set_data_partition
    self.partition = self.create_data_partition()
  File "/usr/lib/python2.7/site-packages/ceph_disk/main.py", line 3025, in create_data_partition
    return device.get_partition(partition_number)
  File "/usr/lib/python2.7/site-packages/ceph_disk/main.py", line 1811, in get_partition
    dev = get_partition_dev(self.path, num)
  File "/usr/lib/python2.7/site-packages/ceph_disk/main.py", line 741, in repeat
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/ceph_disk/main.py", line 776, in get_partition_dev
    (pnum, dev, error_msg))
ceph_disk.main.Error: Error: partition 1 for /dev/mapper/vg3-osda2 does not appear to exist in /sys/block/dm-3
`

Any thoughts on how to create multiple OSDs?  Or is there another community for ceph-container and ceph-ansible besides the ceph-users list? 

Thanks!

**Comment by leseb** [comment]
Short answer, ceph-container currently does not implement ceph-volume yet so LVM is not supported.
So currently you can not achieve your multiple OSD per SSD.

About the community, I think there are the OpenStack folks too.
