### ISSUE TITLE
build downloaded release fails

### ISSUE THREAD

**Issue by Raboo** [ceph/ceph-container#1085]
**Bug Report**

What happened:
Building a downloaded release from https://github.com/ceph/ceph-container/releases fails because the build script expects to live in a git repository.

What you expected to happen:
Building a downloaded release works.

How to reproduce it (minimal and precise):
```
curl -J -L -O https://github.com/ceph/ceph-container/archive/v3.0.5.tar.gz
tar xf ceph-container-3.0.5.tar.gz
cd ceph-container-3.0.5
make FLAVORS="luminous,centos,7 luminous,ubuntu,16.04 mimic,centos,7" build
```
```
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git

  CEPH_VERSION      : luminous
  CEPH_POINT_RELEASE:
  DISTRO            : centos
  DISTRO_VERSION    : 7
  HOST_ARCH         : x86_64
  BASEOS_REGISTRY   :
  BASEOS_REPO       : centos
  BASEOS_TAG        : 7
  IMAGES_TO_BUILD   : daemon-base daemon
  STAGING_DIR       : staging/luminous--centos-7-x86_64
  RELEASE           :
  DAEMON_BASE_IMAGE : ceph/daemon-base:-luminous-centos-7-x86_64
  DAEMON_IMAGE      : ceph/daemon:-luminous-centos-7-x86_64

Computed:
  BASE_IMAGE        : centos:7

fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
Traceback (most recent call last):
  File "maint-lib/stage.py", line 116, in <module>
    main(CORE_FILES_DIR, CEPH_RELEASES_DIR)
  File "maint-lib/stage.py", line 103, in main
    copy_files(src_files, src_path, staging_path, files_copied)
  File "/Users/raboo/repos/ceph-container-3.0.5/maint-lib/stagelib/filetools.py", line 69, in copy_files
    dirty_marker = '*' if git.file_is_dirty(file_path) else ' '
  File "/Users/raboo/repos/ceph-container-3.0.5/maint-lib/stagelib/git.py", line 39, in file_is_dirty
    if re.match(r'^\s*' + file_path + '$', file_status_msg):
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/re.py", line 172, in match
    return _compile(pattern, flags).match(string)
TypeError: expected string or bytes-like object
make: *** [stage.x86_64,luminous,centos,7] Error 1
```

**Build Environment**:
* OS: OS X
* Kernel: Darwin 16.7.0
* Docker version: 18.03.1-ce

**Comment by leseb** [comment]
@BlaineEXE mind having a look into this? Not sure how git can be avoided at the moment, thanks.

**Comment by BlaineEXE** [comment]
The builds expect to be done from the git repo. Among other things, containers are built with git metadata attached so that we know exactly what version of  ceph-container was built.

I think it will be quite a bit of work to support non-git environments. We can talk about supporting this, but the best way to do builds now is:
```
git clone https://github.com/ceph/ceph-container  
git checkout tags/v3.0.5
make FLAVORS="luminous,centos,7 luminous,ubuntu,16.04 mimic,centos,7" build
```

**Comment by Raboo** [comment]
That's what I did (`git checkout v3.0.5`) as a work-around. But I figured since there are releases to download, there should be a way to build them. But that is not important to me. So I will close this issue. What would be even better if there were a docker hub repo with only the "stable" releases.

**Comment by BlaineEXE** [comment]
> What would be even better if there were a docker hub repo with only the "stable" releases.

@Raboo, stable releases can be found in the Docker Hub registry: https://hub.docker.com/r/ceph/daemon/tags/

**Comment by Raboo** [comment]
@BlaineEXE I only see latest and master, no tagged releases.

**Comment by BlaineEXE** [comment]
I don't see it either, though I'm on mobile, which might make a difference.
We build LOTS of different images, so it would have been over a month ago I
think. I don't think dockerhub deletes images does it?

@leseb, maybe we should always build the latest stable release along with
the regular matter releases so it's always visible on the first page?

**Comment by Raboo** [comment]
@BlaineEXE Im using a computer. There is no pagination on docker hub.. I'll reopen this issue until it's sorted out then.

**Comment by leseb** [comment]
@Raboo I guess Docker Hub does not show all the tags. You can query the API though: `https://registry.hub.docker.com/v2/repositories/ceph/daemon/tags/?page=1` or use https://github.com/ceph/cn which can list all the images for you.

**Comment by leseb** [comment]
```
cn image ls --all | grep stable                                                                                                                                                                                                                                                                   ⏎
v3.0.5-stable-3.0-luminous-centos-7
v3.0.5-stable-3.0-jewel-centos-7-x86_64
v3.0.5-stable-3.0-kraken-centos-7-x86_64
v3.0.5-stable-3.0-kraken-ubuntu-16.04-x86_64
v3.0.5-stable-3.0-jewel-ubuntu-16.04-x86_64
v3.0.5-stable-3.0-jewel-ubuntu-14.04-x86_64
v3.0.5-stable-3.0-luminous-centos-7-x86_64
v3.0.5-stable-3.0-luminous-ubuntu-16.04-x86_64
v3.0.5-stable-3.0-luminous-centos-7-aarch64
v3.0.3-stable-3.0-kraken-ubuntu-16.04-x86_64
v3.0.3-stable-3.0-jewel-centos-7-x86_64
v3.0.3-stable-3.0-jewel-ubuntu-16.04-x86_64
v3.0.3-stable-3.0-jewel-ubuntu-14.04-x86_64
v3.0.3-stable-3.0-luminous-centos-7-x86_64
v3.0.3-stable-3.0-luminous-ubuntu-16.04-x86_64
v3.0.3-stable-3.0-kraken-centos-7-x86_64
v3.0.2-stable-3.0-jewel-ubuntu-14.04-x86_64
v3.0.2-stable-3.0-kraken-centos-7-x86_64
v3.0.2-stable-3.0-jewel-ubuntu-16.04-x86_64
v3.0.2-stable-3.0-kraken-ubuntu-16.04-x86_64
v3.0.2-stable-3.0-luminous-centos-7-x86_64
v3.0.2-stable-3.0-luminous-ubuntu-16.04-x86_64
v3.0.2-stable-3.0-jewel-centos-7-x86_64
v3.0.1-stable-3.0-jewel-ubuntu-16.04-x86_64
v3.0.1-stable-3.0-kraken-centos-7-x86_64
v3.0.1-stable-3.0-jewel-ubuntu-14.04-x86_64
v3.0.1-stable-3.0-kraken-ubuntu-16.04-x86_64
v3.0.1-stable-3.0-luminous-centos-7-x86_64
v3.0.1-stable-3.0-luminous-ubuntu-16.04-x86_64
v3.0.1-stable-3.0-jewel-centos-7-x86_64
tag-stable-3.0-luminous-ubuntu-16.04
tag-stable-3.0-luminous-centos-7
tag-stable-3.0-jewel-centos-7
```

**Comment by Raboo** [comment]
Ok, cool. Kind of bad that docker hub doesn't show all images. I'm guessing I won't be the only one with this issue. Should I add a list of these stable images to the README.md?

**Comment by leseb** [comment]
@Raboo please do :)
