### ISSUE TITLE
Guides for setting up iSCSI on Docker container Ubuntu 16.04 HOST?

### ISSUE THREAD

**Issue by mnkdstock** [ceph/ceph-container#1118]
Hi I'm currently in the process of setting up iSCSI on the docker containers. It looks like I need to start 3x containers for (tcmu_runner,  rbd_target_api and  rbd_target_gw)  Do we have any guides for setting up iSCSI on docker containers? 

Running:
`docker run -d --net=host --pid=host --privileged=true -v /etc/ceph:/etc/ceph -v/dev:/dev -e OSD_DEVICE=/dev/sdb ceph/daemon rbd_target_api`

error:
'2018-07-19 02:59:07  /entrypoint.sh: static: does not generate config
HEALTH_OK
2018-07-19 02:59:08  /entrypoint.sh: SUCCESS
exec: PID 21619: spawning /usr/bin/rbd-target-api
Traceback (most recent call last):
  File "/usr/bin/rbd-target-api", line 2010, in <module>
    syslog_handler = logging.handlers.SysLogHandler(address='/dev/log')
  File "/usr/lib64/python2.7/logging/handlers.py", line 761, in __init__
    self._connect_unixsocket(address)
  File "/usr/lib64/python2.7/logging/handlers.py", line 789, in _connect_unixsocket
    self.socket.connect(address)
  File "/usr/lib64/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 2] No such file or directory'

**Comment by mnkdstock** [comment]
To fix the error above. I had to pass in 2 directories below.  (note 2nd one because the first one is symbolic link) 

-v /dev:/dev -v /run/systemd/journal:/run/systemd/journal

'docker run -d --net=host --privileged=true  -p 5000:5000 -v /etc/ceph:/etc/ceph -v /dev:/dev -v /run/systemd/journal:/run/systemd/journal  ceph/daemon rbd_target_api'

**Comment by mnkdstock** [comment]
Just wanted to update. iSCSI works in a containers using following OS and kernel versions
Container host OS: Centos 7
Container Host Kernel version: 4.17.10-1.el7.elrepo.x86_64

**Comment by mnkdstock** [comment]
I was able to have this working on Ubuntu 16.04 host running kernel version 4.17.10-041710-generic.
