### ISSUE TITLE
environ TypeError: <lambda>() takes exactly 1 argument (2 given)

### ISSUE THREAD

**Issue by Helenbj** [ceph/ceph-container#1402]
Is this a bug report or feature request?
* yes

**Bug Report**

When I run “./create_ceph_cluster.sh”， error：

```
+ ./create_secrets.sh
+ cd generator
++ ./generate_secrets.sh fsid
+ ./generate_secrets.sh all ea52ed4b-af72-4ab1-853b-413d1b3aa429
Traceback (most recent call last):
  File "/usr/local/bin/jinja2", line 11, in <module>
    load_entry_point('jinja2-cli==0.7.0', 'console_scripts', 'jinja2')()
  File "/usr/local/lib/python2.7/dist-packages/jinja2_cli-0.7.0-py2.7.egg/jinja2cli/cli.py", line 425, in main
    sys.exit(cli(opts, args))
  File "/usr/local/lib/python2.7/dist-packages/jinja2_cli-0.7.0-py2.7.egg/jinja2cli/cli.py", line 315, in cli
    out.write(render(template_path, data, extensions, opts.strict))
  File "/usr/local/lib/python2.7/dist-packages/jinja2_cli-0.7.0-py2.7.egg/jinja2cli/cli.py", line 230, in render
    return env.get_template(os.path.basename(template_path)).render(data)
  File "/usr/local/lib/python2.7/dist-packages/Jinja2-2.10.1-py2.7.egg/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/dist-packages/Jinja2-2.10.1-py2.7.egg/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/nsr/ceph-container/examples/kubernetes/generator/templates/ceph/ceph.conf.jinja", line 3, in top-level template code
    cephx = {{ environ("auth_cephx", "true") }}
TypeError: <lambda>() takes exactly 1 argument (2 given)
+ kubectl create namespace ceph
Error from server (AlreadyExists): namespaces "ceph" already exists
```

What happened:

The file “ceph-container/examples/kubernetes/generator/templates/ceph/ceph.conf.jinja” as follow:

```
[global]
fsid = {{ fsid }}
cephx = {{ environ("auth_cephx", "true") }}
cephx_require_signatures = {{ environ("auth_cephx_require_signatures", "false") }}
cephx_cluster_require_signatures = {{ environ("auth_cephx_cluster_require_signatures", "true") }}
cephx_service_require_signatures = {{ environ("auth_cephx_service_require_signatures", "false") }}

# auth
max_open_files = {{ environ("global_max_open_files", "131072") }}
osd_pool_default_pg_num = {{ environ("global_osd_pool_default_pg_num", "128") }}
osd_pool_default_pgp_num = {{ environ("global_osd_pool_default_pgp_num", "128") }}
osd_pool_default_size = {{ environ("global_osd_pool_default_size", "3") }}
osd_pool_default_min_size = {{ environ("global_osd_pool_default_min_size", "1") }}

mon_osd_full_ratio = {{ environ("global_mon_osd_full_ratio", ".95") }}
mon_osd_nearfull_ratio = {{ environ("global_mon_osd_nearfull_ratio", ".85") }}

mon_host = {{ environ("global_mon_host", "ceph-mon") }}

[mon]
mon_osd_down_out_interval = {{ environ("mon_mon_osd_down_out_interval", "600") }}
mon_osd_min_down_reporters = {{ environ("mon_mon_osd_min_down_reporters", "4") }}
mon_clock_drift_allowed = {{ environ("mon_mon_clock_drift_allowed", ".15") }}
mon_clock_drift_warn_backoff = {{ environ("mon_mon_clock_drift_warn_backoff", "30") }}
mon_osd_report_timeout = {{ environ("mon_mon_osd_report_timeout", "300") }}
```

The defination of variable "environ" is in file "/usr/local/lib/python2.7/dist-packages/jinja2_cli-0.7.0-py2.7.egg/jinja2cli/cli.py", as follow:

```
226     # Add environ global
227     env.globals["environ"] = lambda key: force_text(os.environ.get(key))
228     env.globals["get_context"] = lambda: data
```

What you expected to happen:

Create cluster succssfully.

How to reproduce it (minimal and precise):

**Environment**:
* OS Ubuntu16.04:
* Kernel Linux version 4.4.0-146-generic:
* Docker version 18.09.6:
* Ceph version 10.2.11:

Please help me as soon as possible. Tks! 

@hunter @dang @bnoon @andrewschoen

**Comment by dsavineau** [comment]
It seems to come from the jinja2-cli 0.7.0 release. I don't have the issue when using 0.6.0

**Comment by Helenbj** [comment]
@dsavineau Tks for your reply, I have resolve this by modify the file "ceph-container/examples/kubernetes/generator/templates/ceph/ceph.conf.jinja", and now I can finish create. Now the file looks like as follow:

```
ph-container/examples/kubernetes/generator/templates/ceph/ceph.conf.jinja]
fsid = {{ fsid }}
cephx = {{ environ("true") }}
cephx_require_signatures = {{ environ("false") }}
cephx_cluster_require_signatures = {{ environ("true") }}
cephx_service_require_signatures = {{ environ("false") }}

# auth
max_open_files = {{ environ("131072") }}
osd_pool_default_pg_num = {{ environ("128") }}
osd_pool_default_pgp_num = {{ environ("128") }}
osd_pool_default_size = {{ environ("3") }}
osd_pool_default_min_size = {{ environ("1") }}

mon_osd_full_ratio = {{ environ(".95") }}
mon_osd_nearfull_ratio = {{ environ(".85") }}

mon_host = {{ environ("ceph-mon") }}

[mon]
mon_osd_down_out_interval = {{ environ("600") }}
mon_osd_min_down_reporters = {{ environ("4") }}
mon_clock_drift_allowed = {{ environ(".15") }}
mon_clock_drift_warn_backoff = {{ environ("30") }}
mon_osd_report_timeout = {{ environ("300") }}


[osd]
journal_size = {{ environ("100") }}
cluster_network = {{ environ("10.244.0.0/16") }}
public_network = {{ environ("10.244.0.0/16") }}
osd_mkfs_type = {{ environ("xfs") }}
osd_mkfs_options_xfs = {{ environ("-f -i size=2048") }}
osd_mon_heartbeat_interval = {{ environ("30") }}
osd_max_object_name_len = {{ environ("256") }}

#crush
osd_pool_default_crush_rule = {{ environ("0") }}
osd_crush_update_on_start = {{ environ("true") }}

#backend
osd_objectstore = {{ environ("filestore") }}
```

I think this is because the define in jinja2 lib has changed.
