### ISSUE TITLE
cephadm can't download container image because of missing variant property

### ISSUE THREAD

**Issue by XenGi** [ceph/ceph-container#1673]
**Bug Report**

What happened:

I tried using cephadm to deploy a cluster on my Linux aarch64 Board. in the step of downloading the containers the script broke with the folllowing error:

```
$ sudo cephadm bootstrap --mon-ip 192.168.20.156
INFO:cephadm:Verifying podman|docker is present...
INFO:cephadm:Verifying lvm2 is present...
INFO:cephadm:Verifying time synchronization is in place...
INFO:cephadm:Unit systemd-timesyncd.service is enabled and running
INFO:cephadm:Repeating the final host check...
INFO:cephadm:podman|docker (/usr/bin/podman) is present
INFO:cephadm:systemctl is present
INFO:cephadm:lvcreate is present
INFO:cephadm:Unit systemd-timesyncd.service is enabled and running
INFO:cephadm:Host looks OK
INFO:root:Cluster fsid: 2db46a68-dead-beaf-2342-001e06424a37
INFO:cephadm:Verifying IP 192.168.20.156 port 3300 ...
INFO:cephadm:Verifying IP 192.168.20.156 port 6789 ...
INFO:cephadm:Mon IP 192.168.20.156 is in CIDR network 192.168.20.0/24
INFO:cephadm:Pulling latest docker.io/ceph/ceph:v15 container...
INFO:cephadm:Non-zero exit code 125 from /usr/bin/podman pull docker.io/ceph/ceph:v15
INFO:cephadm:/usr/bin/podman:stderr Trying to pull docker.io/ceph/ceph:v15...
INFO:cephadm:/usr/bin/podman:stderr   no image found in manifest list for architecture arm64, variant v8, OS linux
INFO:cephadm:/usr/bin/podman:stderr Error: error pulling image "docker.io/ceph/ceph:v15": unable to pull docker.io/ceph/ceph:v15: unable to pull image: Error choosing an image from manifest list docker://ceph/ceph:v15: no image found in manifest list for architecture arm64, variant v8, OS linux
Traceback (most recent call last):
  File "/usr/local/bin/cephadm", line 4579, in <module>
    r = args.func()
  File "/usr/local/bin/cephadm", line 1122, in _default_image
    return func()
  File "/usr/local/bin/cephadm", line 2292, in command_bootstrap
    call_throws([container_path, 'pull', args.image])
  File "/usr/local/bin/cephadm", line 837, in call_throws
    raise RuntimeError('Failed command: %s' % ' '.join(command))
RuntimeError: Failed command: /usr/bin/podman pull docker.io/ceph/ceph:v15
```
I inspected the image with docker and found the problem:

```json
$ docker --config .config/docker manifest inspect ceph/ceph:v15
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 743,
         "digest": "sha256:9c0453a47983337520bf7efe5154a501c4d934cb3fced3d5a362f3b02871ab4e",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 743,
         "digest": "sha256:97f81ff40202c923b080ee708eb31077a2c04bc7d9dcb4f862a3a578770f68f6",
         "platform": {
            "architecture": "arm64",
            "os": "linux"
         }
      }
   ]
}
```

In there you can see that the arm64 image is missing the `"variant": "v8"` property. You can see a working example in the docker image from drone:

```json
$ docker --config .config/docker manifest inspect drone/drone:latest
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1157,
         "digest": "sha256:400f1138bc632a9e8aec05948c79224dbcc2cdbd52d2b4b39894f4a75e5ad24d",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1157,
         "digest": "sha256:7755e0d71c6c8a1a1e88018a2e7c5734e81663d4ecc9e40421053bcf7e80e1d4",
         "platform": {
            "architecture": "arm64",
            "os": "linux",
            "variant": "v8"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1157,
         "digest": "sha256:57f9e54cde57ffa6beaafc0cb47e85a813e47981a413ffa5adb2fbf6f90545b8",
         "platform": {
            "architecture": "arm",
            "os": "linux",
            "variant": "v7"
         }
      }
   ]
}
```
For me there seems to be two solutions. Either the image gets the `"variant": "v8"` property or the cephadm tool stops looking for it. I don't know which approach is better here.

What you expected to happen:

Bootstrapping should go through with no error. Everything seems to be ok. When I lookup dockerhub I can find the arm64 image.

How to reproduce it (minimal and precise):

- Use any aarch64 board
- Install Arch Linux ARM or any other aarch64 Linux
- Install podman, lvm2 and python3
- Run the cephadm bootstrap command from above

**Environment**:
* OS (e.g. from /etc/os-release): Arch Linux ARM
* Kernel (e.g. `uname -a`): 4.9.219-1-ARCH
* Docker version (e.g. `docker version`): 19.03.8-ce
* Podman version: 1.9.1
* Ceph version (e.g. `ceph -v`): v15 tag from dockerhub

**Comment by dsavineau** [comment]
> For me there seems to be two solutions. Either the image gets the "variant": "v8" property or the cephadm tool stops looking for it. I don't know which approach is better here.

Looks like adding "variant: v8" is the only way to fix this but I quite surprise that nobody reports this before.
Are you able to pull the image with podman and/or docker on arm64 via docker.io/ceph/ceph:v15 ?

Note that this isn't related to cephadm at all since this tool only rely on the pull subcommand from docker/podman and doesn't use any variant/platform option.

As a workaround you can try to use the `docker.io/ceph/ceph-arm64:v15.2.1-20200410` container image which is the direct container image without using the manifest.

I'm very surprised that the arm64 platform requires the "variant: v8" option especially because there's no other variable for that architecture (at least for the moment).

**Comment by XenGi** [comment]
I haven't tried but my guess was that docker is probably not that picky about it and most people simply use docker. Podman seems to be more "standard conform" and wants the variant.
Also the "v8" is the only one at the moment but there will be a v9 in the future. ;)

**Comment by dsavineau** [comment]
This is fixed on the current images too.

```console
$ docker manifest inspect ceph/ceph:v15
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 743,
         "digest": "sha256:9c0453a47983337520bf7efe5154a501c4d934cb3fced3d5a362f3b02871ab4e",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 743,
         "digest": "sha256:97f81ff40202c923b080ee708eb31077a2c04bc7d9dcb4f862a3a578770f68f6",
         "platform": {
            "architecture": "arm64",
            "os": "linux",
            "variant": "v8"
         }
      }
   ]
}
```

Could you try again ?
