### ISSUE TITLE
Image not found (16.2.6)

### ISSUE THREAD

**Issue by sw0x2A** [ceph/ceph-container#1957]
Is this a bug report or feature request?
* Bug Report

**Bug Report**

What happened:

I have upgraded our cluster to 16.2.6 the day after it was released (2021-09-17). I used the following command:
`sudo ceph orch upgrade start --image quay.io/ceph/ceph:v16.2.6`

I want to add a new host to cluster now but image cannot be found.
`sudo ceph orch host add myhost 172.42.5.51`

```
# ceph health detail
HEALTH_WARN failed to probe daemons or devices
[WRN] CEPHADM_REFRESH_FAILED: failed to probe daemons or devices
    host myhost `cephadm ceph-volume` failed: cephadm exited with an error code: 1, stderr:Non-zero exit code 125 from /usr/bin/docker run --rm --ipc=host --stop-signal=SIGTERM --net=host --entrypoint stat --init -e CONTAINER_IMAGE=quay.io/ceph/ceph@sha256:5d042251e1faa1408663508099cf97b256364300365d403ca5563a518060abac -e NODE_NAME=cephosd-6.tor.rgcloud.net -e CEPH_USE_RANDOM_NONCE=1 quay.io/ceph/ceph@sha256:5d042251e1faa1408663508099cf97b256364300365d403ca5563a518060abac -c %u %g /var/lib/ceph
stat: stderr Unable to find image 'quay.io/ceph/ceph@sha256:5d042251e1faa1408663508099cf97b256364300365d403ca5563a518060abac' locally
stat: stderr docker: Error response from daemon: manifest for quay.io/ceph/ceph@sha256:5d042251e1faa1408663508099cf97b256364300365d403ca5563a518060abac not found: manifest unknown: manifest unknown.
stat: stderr See 'docker run --help'.
Traceback (most recent call last):
  File "/var/lib/ceph/24505b76-7020-4ff6-bb76-b01437c01ac4/cephadm.f46dc95b01feeedb28941a48e2f1d0abb51139ca828de11150ea7122a8e3549c", line 8479, in <module>
    main()
  File "/var/lib/ceph/24505b76-7020-4ff6-bb76-b01437c01ac4/cephadm.f46dc95b01feeedb28941a48e2f1d0abb51139ca828de11150ea7122a8e3549c", line 8467, in main
    r = ctx.func(ctx)
  File "/var/lib/ceph/24505b76-7020-4ff6-bb76-b01437c01ac4/cephadm.f46dc95b01feeedb28941a48e2f1d0abb51139ca828de11150ea7122a8e3549c", line 1732, in _infer_config
    return func(ctx)
  File "/var/lib/ceph/24505b76-7020-4ff6-bb76-b01437c01ac4/cephadm.f46dc95b01feeedb28941a48e2f1d0abb51139ca828de11150ea7122a8e3549c", line 1673, in _infer_fsid
    return func(ctx)
  File "/var/lib/ceph/24505b76-7020-4ff6-bb76-b01437c01ac4/cephadm.f46dc95b01feeedb28941a48e2f1d0abb51139ca828de11150ea7122a8e3549c", line 1760, in _infer_image
    return func(ctx)
  File "/var/lib/ceph/24505b76-7020-4ff6-bb76-b01437c01ac4/cephadm.f46dc95b01feeedb28941a48e2f1d0abb51139ca828de11150ea7122a8e3549c", line 1660, in _validate_fsid
    return func(ctx)
  File "/var/lib/ceph/24505b76-7020-4ff6-bb76-b01437c01ac4/cephadm.f46dc95b01feeedb28941a48e2f1d0abb51139ca828de11150ea7122a8e3549c", line 4720, in command_ceph_volume
    make_log_dir(ctx, ctx.fsid)
  File "/var/lib/ceph/24505b76-7020-4ff6-bb76-b01437c01ac4/cephadm.f46dc95b01feeedb28941a48e2f1d0abb51139ca828de11150ea7122a8e3549c", line 1862, in make_log_dir
    uid, gid = extract_uid_gid(ctx)
  File "/var/lib/ceph/24505b76-7020-4ff6-bb76-b01437c01ac4/cephadm.f46dc95b01feeedb28941a48e2f1d0abb51139ca828de11150ea7122a8e3549c", line 2585, in extract_uid_gid
    raise RuntimeError('uid/gid not found')
RuntimeError: uid/gid not found
```

It seems the image has been removed or replaced.

What you expected to happen:

Fetch the image and add the node.

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu Focal 20.4
* Kernel (e.g. `uname -a`): 5.11.0-37-generic
* Docker version (e.g. `docker version`): Docker CE 20.10.7
* Ceph version (e.g. `ceph -v`): `ceph version 16.2.6 (ee28fb57e47e9f88813e24bbf4c14496ca299d31) pacific (stable)`

**Comment by sw0x2A** [comment]
I run `sudo ceph orch upgrade start --image quay.io/ceph/ceph:v16.2.6` again which updated the used image and allowed me to proceed with adding the new host.

I think the issue is that you rebuild images of a particular version and cleanup older ones after a while but the cluster searches images not by tag but by checksum. 
```
% curl -s -L https://quay.io/api/v1/repository/ceph/ceph/tag\?page_size\=1000 | jq '."tags"[] .name'|grep '16.2.6'

"v16.2.6"
"v16.2.6-20210927"
"v16.2.6"
"v16.2.6-20210926"
"v16.2.6"
"v16.2.6-20210925"
"v16.2.6"
"v16.2.6-20210924"
"v16.2.6"
"v16.2.6-20210923"
"v16.2.6"
"v16.2.6-20210918"
"v16.2.6"
"v16.2.6"
"v16.2.6-20210918"
```
