### ISSUE TITLE
Ceph 15 - add osd results in Executable udevadm not in PATH

### ISSUE THREAD

**Issue by T0mWz** [ceph/ceph-container#1984]
Trying to setup a new Ceph Cluster with use of cephadm.
When I will add an OSD I got the error;
```
RuntimeError: cephadm exited with an error code: 1, stderr:/usr/bin/docker: stderr --> Executable udevadm not in PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
/usr/bin/docker: stderr -->  FileNotFoundError: [Errno 2] No such file or directory: 'udevadm': 'udevadm'
```

Full trace of ceph command.

```
[root@mouse1 ~]# ceph orch daemon add osd mouse4:/dev/sdb
Error EINVAL: Traceback (most recent call last):
  File "/usr/share/ceph/mgr/mgr_module.py", line 1212, in _handle_command
    return self.handle_command(inbuf, cmd)
  File "/usr/share/ceph/mgr/orchestrator/_interface.py", line 140, in handle_command
    return dispatch[cmd['prefix']].call(self, cmd, inbuf)
  File "/usr/share/ceph/mgr/mgr_module.py", line 320, in call
    return self.func(mgr, **kwargs)
  File "/usr/share/ceph/mgr/orchestrator/_interface.py", line 102, in <lambda>
    wrapper_copy = lambda *l_args, **l_kwargs: wrapper(*l_args, **l_kwargs)
  File "/usr/share/ceph/mgr/orchestrator/_interface.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/usr/share/ceph/mgr/orchestrator/module.py", line 781, in _daemon_add_osd
    raise_if_exception(completion)
  File "/usr/share/ceph/mgr/orchestrator/_interface.py", line 642, in raise_if_exception
    raise e
RuntimeError: cephadm exited with an error code: 1, stderr:/usr/bin/docker: stderr --> Executable udevadm not in PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
/usr/bin/docker: stderr -->  FileNotFoundError: [Errno 2] No such file or directory: 'udevadm': 'udevadm'
Traceback (most recent call last):
  File "<stdin>", line 6251, in <module>
  File "<stdin>", line 1359, in _infer_fsid
  File "<stdin>", line 1442, in _infer_image
  File "<stdin>", line 3713, in command_ceph_volume
  File "<stdin>", line 1121, in call_throws
RuntimeError: Failed command: /usr/bin/docker run --rm --ipc=host --net=host --entrypoint /usr/sbin/ceph-volume --privileged --group-add=disk -e CONTAINER_IMAGE=quay.io/ceph/ceph:v15 -e NODE_NAME=mouse4 -e CEPH_VOLUME_OSDSPEC_AFFINITY=None -v /var/run/ceph/79903ec0-8074-11ec-91c9-246e9639dadc:/var/run/ceph:z -v /var/log/ceph/79903ec0-8074-11ec-91c9-246e9639dadc:/var/log/ceph:z -v /var/lib/ceph/79903ec0-8074-11ec-91c9-246e9639dadc/crash:/var/lib/ceph/crash:z -v /dev:/dev -v /run/udev:/run/udev -v /sys:/sys -v /run/lvm:/run/lvm -v /run/lock/lvm:/run/lock/lvm -v /tmp/ceph-tmp5nu7dia4:/etc/ceph/ceph.conf:z -v /tmp/ceph-tmp5tm9icq7:/var/lib/ceph/bootstrap-osd/ceph.keyring:z quay.io/ceph/ceph:v15 lvm batch --no-auto /dev/sdb --yes --no-systemd
```

However `udevadm` looks fine on that machine;
```
[root@mouse4 ~]# udevadm info --query=property /dev/sdb
DEVLINKS=/dev/disk/by-id/lvm-pv-uuid-3JZyc5-CXyH-fJwY-3K9j-IDRv-yUqn-i9vNXG /dev/disk/by-id/scsi-361866da090723700298be5501b85ae68 /dev/disk/by-id/wwn-0x61866da090723700298be5501b85ae68 /dev/disk/by-path/pci-0000:02:00.0-scsi-0:2:1:0
DEVNAME=/dev/sdb
DEVPATH=/devices/pci0000:00/0000:00:01.0/0000:02:00.0/host0/target0:2:1/0:2:1:0/block/sdb
DEVTYPE=disk
```

What I see in the ceph log on this machine;
```
2022-02-01 14:40:38,445 7fec3f7a4740 DEBUG container_init=False
2022-02-01 14:40:38,446 7fec3f7a4740 DEBUG Using specified fsid: 79903ec0-8074-11ec-91c9-246e9639dadc
2022-02-01 14:40:38,446 7fec3f7a4740 DEBUG Running command: /usr/bin/docker run --rm --ipc=host --net=host --entrypoint stat -e CONTAINER_IMAGE=quay.io/ceph/ceph:v15 -e NODE_NAME=mouse4 quay.io/ceph/ceph:v15 -c %u %g /var/lib/ceph
2022-02-01 14:40:38,633 7fec3f7a4740 DEBUG stat: stdout 167 167
2022-02-01 14:40:38,666 7fec3f7a4740 DEBUG Acquiring lock 140652516776760 on /run/cephadm/79903ec0-8074-11ec-91c9-246e9639dadc.lock
2022-02-01 14:40:38,667 7fec3f7a4740 DEBUG Lock 140652516776760 acquired on /run/cephadm/79903ec0-8074-11ec-91c9-246e9639dadc.lock
2022-02-01 14:40:38,668 7fec3f7a4740 DEBUG Running command: /usr/bin/docker run --rm --ipc=host --net=host --entrypoint /usr/sbin/ceph-volume --privileged --group-add=disk -e CONTAINER_IMAGE=quay.io/ceph/ceph:v15 -e NODE_NAME=mouse4 -e CEPH_VOLUME_OSDSPEC_AFFINITY=None -v /var/run/ceph/79903ec0-8074-11ec-91c9-246e9639dadc:/var/run/ceph:z -v /var/log/ceph/79903ec0-8074-11ec-91c9-246e9639dadc:/var/log/ceph:z -v /var/lib/ceph/79903ec0-8074-11ec-91c9-246e9639dadc/crash:/var/lib/ceph/crash:z -v /dev:/dev -v /run/udev:/run/udev -v /sys:/sys -v /run/lvm:/run/lvm -v /run/lock/lvm:/run/lock/lvm -v /tmp/ceph-tmp5nu7dia4:/etc/ceph/ceph.conf:z -v /tmp/ceph-tmp5tm9icq7:/var/lib/ceph/bootstrap-osd/ceph.keyring:z quay.io/ceph/ceph:v15 lvm batch --no-auto /dev/sdb --yes --no-systemd
2022-02-01 14:40:39,340 7fec3f7a4740 INFO /usr/bin/docker: stderr --> Executable udevadm not in PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
2022-02-01 14:40:39,341 7fec3f7a4740 INFO /usr/bin/docker: stderr -->  FileNotFoundError: [Errno 2] No such file or directory: 'udevadm': 'udevadm'
2022-02-01 14:40:39,341 7fec3f7a4740 DEBUG /usr/bin/docker: profile rt=0.6717898845672607, stop=False, exit=None, reads=[9]
2022-02-01 14:40:39,416 7fec3f7a4740 DEBUG /usr/bin/docker: profile rt=0.7462379932403564, stop=False, exit=1, reads=[7, 9]
2022-02-01 14:40:39,416 7fec3f7a4740 DEBUG /usr/bin/docker: profile rt=0.7466130256652832, stop=True, exit=1, reads=[7, 9]
2022-02-01 14:40:39,425 7fec3f7a4740 DEBUG Releasing lock 140652516776760 on /run/cephadm/79903ec0-8074-11ec-91c9-246e9639dadc.lock
2022-02-01 14:40:39,426 7fec3f7a4740 DEBUG Lock 140652516776760 released on /run/cephadm/79903ec0-8074-11ec-91c9-246e9639dadc.lock
```

Also when I try it manual, it look likes the executable is not in the container;
```
[root@mouse4 ~]# /usr/bin/docker run --rm --ipc=host --net=host --entrypoint /usr/sbin/ceph-volume --privileged --group-add=disk -e CONTAINER_IMAGE=quay.io/ceph/ceph:v15 -e NODE_NAME=mouse4 -v /var/run/ceph/79903ec0-8074-11ec-91c9-246e9639dadc:/var/run/ceph:z -v /var/log/ceph/79903ec0-8074-11ec-91c9-246e9639dadc:/var/log/ceph:z -v /var/lib/ceph/79903ec0-8074-11ec-91c9-246e9639dadc/crash:/var/lib/ceph/crash:z -v /dev:/dev -v /run/udev:/run/udev -v /sys:/sys -v /run/lvm:/run/lvm -v /run/lock/lvm:/run/lock/lvm quay.io/ceph/ceph:v15 inventory --format=json --filter-for-batch
--> Executable udevadm not in PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
-->  FileNotFoundError: [Errno 2] No such file or directory: 'udevadm': 'udevadm'
```

Also when I mount the container direct, it's not there.
```
[root@mouse4 ~]# docker run -it --rm quay.io/ceph/ceph:v15 bash
[root@3e7f7f79ba21 /]# which udevadm
/usr/bin/which: no udevadm in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin)
```

**Environment**:
* OS : CentOS Linux release 7.9.2009 (Core)
* Kernel : Linux mouse4 5.8.1-1.el7.elrepo.x86_64
* Docker version : 20.10.12
* Ceph version : ceph version 15.2.15 (2dfb18841cfecc2f7eb7eb2afd65986ca4d95985) octopus (stable)
```
REPOSITORY                         TAG       IMAGE ID       CREATED       SIZE
quay.io/ceph/ceph                  v15       118f0eb90179   4 hours ago   1.32GB

[root@mouse4 ~]# docker image inspect 118f0eb90179
[
    {
        "Id": "sha256:118f0eb901792f2d2f20de2afcfd4276ede2f0bd8c67d542876790d817400cce",
        "RepoTags": [
            "quay.io/ceph/ceph:v15"
        ],
        "RepoDigests": [
            "quay.io/ceph/ceph@sha256:5d31d7ea2b8de023600470aa2250812688dbc4f31e76ea6960c0fbed44f14d45"
        ],
        "Parent": "",
        "Comment": "",
        "Created": "2022-02-01T09:46:14.378079175Z",
        "Container": "a01f976ee53f85a7d25639f355e5972eca85c32fd889559803947693912b3a53",
```

**Comment by TomHellier** [comment]
It looks like they've just re-released all of their latest images

https://quay.io/repository/ceph/ceph?tab=tags

this is a pretty big breaking change we're seeing on our clusters

**Comment by TomHellier** [comment]
@guits
