### ISSUE TITLE
"systemctl start ceph-osd" fails with "failed to connect to bus"

### ISSUE THREAD

**Issue by kwtalley** [ceph/ceph-container#476]
hey all,

I've got the following setup:
- kubernetes 1.5.1
- Docker version 1.12.6, build 78d1802
- either OS: centos 7.3.1611 (kernel 3.10.0-514.el7.x86_64), ubuntu 16.04 (kernel 4.4)
- currently testing with centos 7.3.1611

when deploying osds to the nodes, all disk operations are successful (prepare, activate, format, etc), but then will error with the following:

`2017-02-02T18:15:23.344791346Z command_check_call: Running command: /bin/systemctl disable ceph-osd@9
2017-02-02T18:15:23.353848220Z command_check_call: Running command: /bin/systemctl enable --runtime ceph-osd@9
2017-02-02T18:15:23.357343204Z Created symlink /run/systemd/system/ceph-osd.target.wants/ceph-osd@9.service, pointing to /lib/systemd/system/ceph-osd@.service.
2017-02-02T18:15:23.357904257Z command_check_call: Running command: /bin/systemctl start ceph-osd@9
2017-02-02T18:15:23.360610145Z Failed to connect to bus: No such file or directory
2017-02-02T18:15:23.360860324Z Traceback (most recent call last):
2017-02-02T18:15:23.360876196Z   File "/usr/sbin/ceph-disk", line 9, in <module>
2017-02-02T18:15:23.360884558Z     load_entry_point('ceph-disk==1.0.0', 'console_scripts', 'ceph-disk')()
2017-02-02T18:15:23.360890955Z   File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 5230, in run
2017-02-02T18:15:23.362132219Z     main(sys.argv[1:])
2017-02-02T18:15:23.362150921Z   File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 5181, in main
2017-02-02T18:15:23.363146093Z     args.func(args)
2017-02-02T18:15:23.363157499Z   File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 3570, in main_activate
2017-02-02T18:15:23.363775056Z     osd_id=osd_id,
2017-02-02T18:15:23.363787346Z   File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 3109, in start_daemon
2017-02-02T18:15:23.364281107Z     raise Error('ceph osd start failed', e)
2017-02-02T18:15:23.364361496Z ceph_disk.main.Error: <exception str() failed>`

google hasn't really turned up anything useful yet...

Thanks!

**Comment by leseb** [comment]
It looks like ceph-disk tries to run the container with systemd. We have proposed a patch to get a better support of ceph-disk in container, starting with `ceph-detect-init`, https://github.com/ceph/ceph/pull/13218 (thanks @guits). We are not done yet.
To be honest I thought we fixed that problem. Are you running Jewel or Kraken?

Can you tell me which part of the entrypoint is this? How did you run the container?
And btw the error is normal, there is no systemd inside the container :)

**Comment by font** [comment]
What version of the ceph-docker container were you using i.e. ceph/daemon:<tag>? I think https://github.com/ceph/ceph-docker/pull/478 may address this. Try it and see if it fixes it.

**Comment by leseb** [comment]
Try to pull the image again. You will get the fix.
