### ISSUE TITLE
osd fails to initialize bluestore disk

### ISSUE THREAD

**Issue by farcaller** [ceph/ceph-container#477]
OSD is configured with:

* `OSD_DEVICE=/dev/lv/osd_1`
* `OSD_TYPE=disk`
* `OSD_BLUESTORE=1`
* `OSD_FORCE_ZAP=1`

/dev/lv/osd_1 is lvm symlink to /dev/dm-40

```
2017-02-05 10:38:21 ceph_osd_1: Traceback (most recent call last):
2017-02-05 10:38:21 ceph_osd_1:   File "/usr/sbin/ceph-disk", line 9, in <module>
2017-02-05 10:38:21 ceph_osd_1:     load_entry_point('ceph-disk==1.0.0', 'console_scripts', 'ceph-disk')()
2017-02-05 10:38:21 ceph_osd_1:   File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 5230, in run
2017-02-05 10:38:21 ceph_osd_1:     main(sys.argv[1:])
2017-02-05 10:38:21 ceph_osd_1:   File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 5181, in main
2017-02-05 10:38:21 ceph_osd_1:     args.func(args)
2017-02-05 10:38:21 ceph_osd_1:   File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 1874, in main
2017-02-05 10:38:21 ceph_osd_1:     Prepare.factory(args).prepare()
2017-02-05 10:38:21 ceph_osd_1:   File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 1863, in prepare
2017-02-05 10:38:21 ceph_osd_1:     self.prepare_locked()
2017-02-05 10:38:21 ceph_osd_1:   File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 1935, in prepare_locked
2017-02-05 10:38:21 ceph_osd_1:     self.data.prepare(*to_prepare_list)
2017-02-05 10:38:21 ceph_osd_1:   File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 2653, in prepare
2017-02-05 10:38:21 ceph_osd_1:     self.prepare_device(*to_prepare_list)
2017-02-05 10:38:21 ceph_osd_1:   File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 2836, in prepare_device
2017-02-05 10:38:21 ceph_osd_1:     self.set_data_partition()
2017-02-05 10:38:21 ceph_osd_1:   File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 2757, in set_data_partition
2017-02-05 10:38:21 ceph_osd_1:     self.partition = self.create_data_partition()
2017-02-05 10:38:21 ceph_osd_1:     return device.get_partition(partition_number)
2017-02-05 10:38:21 ceph_osd_1:   File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 1601, in get_partition
2017-02-05 10:38:21 ceph_osd_1:   File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 680, in get_partition_dev
2017-02-05 10:38:21 ceph_osd_1:     (pnum, dev))
2017-02-05 10:38:21 ceph_osd_1: ceph_disk.main.Error: Error: partition 1 for /dev/lv/osd_1 does not appear to exist
```

**Comment by leseb** [comment]
I think the issue is that `ceph-disk` does not support lvm at the moment, we need a raw device.

**Comment by farcaller** [comment]
Why would ceph-disk prefer one kind of bock device over another? For all intents and purposes, it shouldn't interact with lvm part, right? DM definitely works on top of another DM device.

**Comment by leseb** [comment]
It's just that ceph-disk doesn't support lvm at the moment, it expects one of the following:

* raw block device, e.g: /dev/sdb
* block device partition, e.g: /dev/sdb1
* directory, e.g: /var/lib/ceph/osd/ceph-0

So it doesn't have the logic to use the lv partition and not create one out of it. It has been added to the roadmap as a potential feature to implement.

**Comment by farcaller** [comment]
ack, makes sense.

**Comment by farcaller** [comment]
Is it possible to link the roadmap note to here so I could track the progress? I'd love to migrate off xfs but this issue is blocking me.

**Comment by alfredodeza** [comment]
@farcaller one ceph-container supports ceph-volume, you will be able to have no issues with logical volumes. There is no roadmap for features in this project (yet). @leseb maybe that could be something useful here as well as in ceph-ansible

**Comment by leseb** [comment]
The current plan is to implement ceph-volume in ceph-container. This is huge and I hope this will be available soon but that's a big change so we have to be careful.
