### ISSUE TITLE
OSD creation fail at mount

### ISSUE THREAD

**Issue by kakawait** [ceph/ceph-container#519]
I'm trying to build Ceph cluster for RBD usage, I'm following http://youtu.be/FUSTjTBA8f8

Just after instantiate `mon` I'm trying to create `osd` but I have following error when executing

`docker run -d --net=host --privileged=true -v /dev/:/dev/ -v $(pwd)/data:/var/lib/ceph -v $(pwd)/conf:/etc/ceph -e OSD_FORCE_ZAP=1 -e OSD_DEVICE=/dev/sdb ceph/daemon osd_ceph_disk`

```
2017-02-27 13:56:02  /entrypoint.sh: static: does not generate config
HEALTH_ERR 64 pgs are stuck inactive for more than 300 seconds; 64 pgs stuck inactive; 64 pgs stuck unclean; no osds
2017-02-27 13:56:02  /entrypoint.sh: It looks like /dev/sdb is an OSD, however OSD_FORCE_ZAP is enabled so we are zapping the device anyway
get_dm_uuid: get_dm_uuid /dev/sdb uuid path is /sys/dev/block/8:16/dm/uuid
zap: Zapping partition table on /dev/sdb
command_check_call: Running command: /sbin/sgdisk --zap-all -- /dev/sdb
Caution: invalid backup GPT header, but valid main header; regenerating
backup header from main header.

Warning! Main and backup partition tables differ! Use the 'c' and 'e' options
on the recovery & transformation menu to examine the two tables.

Warning! One or more CRCs don't match. You should repair the disk!

****************************************************************************
Caution: Found protective or hybrid MBR and corrupt GPT. Using GPT, but disk
verification and recovery are STRONGLY recommended.
****************************************************************************
GPT data structures destroyed! You may now partition the disk using fdisk or
other utilities.
command_check_call: Running command: /sbin/sgdisk --clear --mbrtogpt -- /dev/sdb
Creating new GPT entries.
The operation has completed successfully.
update_partition: Calling partprobe on zapped device /dev/sdb
command_check_call: Running command: /sbin/udevadm settle --timeout=600
command: Running command: /usr/bin/flock -s /dev/sdb /sbin/partprobe /dev/sdb
command_check_call: Running command: /sbin/udevadm settle --timeout=600
command: Running command: /usr/bin/ceph-osd --cluster=ceph --show-config-value=fsid
command: Running command: /usr/bin/ceph-osd --check-allows-journal -i 0 --cluster ceph
command: Running command: /usr/bin/ceph-osd --check-wants-journal -i 0 --cluster ceph
command: Running command: /usr/bin/ceph-osd --check-needs-journal -i 0 --cluster ceph
get_dm_uuid: get_dm_uuid /dev/sdb uuid path is /sys/dev/block/8:16/dm/uuid
set_type: Will colocate journal with data on /dev/sdb
command: Running command: /usr/bin/ceph-osd --cluster=ceph --show-config-value=osd_journal_size
get_dm_uuid: get_dm_uuid /dev/sdb uuid path is /sys/dev/block/8:16/dm/uuid
get_dm_uuid: get_dm_uuid /dev/sdb uuid path is /sys/dev/block/8:16/dm/uuid
get_dm_uuid: get_dm_uuid /dev/sdb uuid path is /sys/dev/block/8:16/dm/uuid
command: Running command: /usr/bin/ceph-conf --cluster=ceph --name=osd. --lookup osd_mkfs_type
command: Running command: /usr/bin/ceph-conf --cluster=ceph --name=osd. --lookup osd_fs_type
command: Running command: /usr/bin/ceph-conf --cluster=ceph --name=osd. --lookup osd_mkfs_options_xfs
command: Running command: /usr/bin/ceph-conf --cluster=ceph --name=osd. --lookup osd_fs_mkfs_options_xfs
command: Running command: /usr/bin/ceph-conf --cluster=ceph --name=osd. --lookup osd_mount_options_xfs
command: Running command: /usr/bin/ceph-conf --cluster=ceph --name=osd. --lookup osd_fs_mount_options_xfs
get_dm_uuid: get_dm_uuid /dev/sdb uuid path is /sys/dev/block/8:16/dm/uuid
get_dm_uuid: get_dm_uuid /dev/sdb uuid path is /sys/dev/block/8:16/dm/uuid
ptype_tobe_for_name: name = journal
get_dm_uuid: get_dm_uuid /dev/sdb uuid path is /sys/dev/block/8:16/dm/uuid
create_partition: Creating journal partition num 2 size 100 on /dev/sdb
command_check_call: Running command: /sbin/sgdisk --new=2:0:+100M --change-name=2:ceph journal --partition-guid=2:c8a7fb34-5aaf-4f68-a401-de9320b8646d --typecode=2:45b0969e-9b03-4f30-b4c6-b4b80ceff106 --mbrtogpt -- /dev/sdb
Setting name!
partNum is 1
REALLY setting name!
The operation has completed successfully.
update_partition: Calling partprobe on created device /dev/sdb
command_check_call: Running command: /sbin/udevadm settle --timeout=600
command: Running command: /usr/bin/flock -s /dev/sdb /sbin/partprobe /dev/sdb
command_check_call: Running command: /sbin/udevadm settle --timeout=600
get_dm_uuid: get_dm_uuid /dev/sdb uuid path is /sys/dev/block/8:16/dm/uuid
get_dm_uuid: get_dm_uuid /dev/sdb uuid path is /sys/dev/block/8:16/dm/uuid
get_dm_uuid: get_dm_uuid /dev/sdb2 uuid path is /sys/dev/block/8:18/dm/uuid
prepare_device: Journal is GPT partition /dev/disk/by-partuuid/c8a7fb34-5aaf-4f68-a401-de9320b8646d
command_check_call: Running command: /sbin/sgdisk --typecode=2:45b0969e-9b03-4f30-b4c6-b4b80ceff106 -- /dev/sdb
The operation has completed successfully.
update_partition: Calling partprobe on prepared device /dev/sdb
command_check_call: Running command: /sbin/udevadm settle --timeout=600
command: Running command: /usr/bin/flock -s /dev/sdb /sbin/partprobe /dev/sdb
command_check_call: Running command: /sbin/udevadm settle --timeout=600
prepare_device: Journal is GPT partition /dev/disk/by-partuuid/c8a7fb34-5aaf-4f68-a401-de9320b8646d
get_dm_uuid: get_dm_uuid /dev/sdb uuid path is /sys/dev/block/8:16/dm/uuid
set_data_partition: Creating osd partition on /dev/sdb
get_dm_uuid: get_dm_uuid /dev/sdb uuid path is /sys/dev/block/8:16/dm/uuid
ptype_tobe_for_name: name = data
get_dm_uuid: get_dm_uuid /dev/sdb uuid path is /sys/dev/block/8:16/dm/uuid
create_partition: Creating data partition num 1 size 0 on /dev/sdb
command_check_call: Running command: /sbin/sgdisk --largest-new=1 --change-name=1:ceph data --partition-guid=1:3295f851-82f9-45e7-87bd-e294ca7f6ef2 --typecode=1:89c57f98-2fe5-4dc0-89c1-f3ad0ceff2be --mbrtogpt -- /dev/sdb
Setting name!
partNum is 0
REALLY setting name!
The operation has completed successfully.
update_partition: Calling partprobe on created device /dev/sdb
command_check_call: Running command: /sbin/udevadm settle --timeout=600
command: Running command: /usr/bin/flock -s /dev/sdb /sbin/partprobe /dev/sdb
command_check_call: Running command: /sbin/udevadm settle --timeout=600
get_dm_uuid: get_dm_uuid /dev/sdb uuid path is /sys/dev/block/8:16/dm/uuid
get_dm_uuid: get_dm_uuid /dev/sdb uuid path is /sys/dev/block/8:16/dm/uuid
get_dm_uuid: get_dm_uuid /dev/sdb1 uuid path is /sys/dev/block/8:17/dm/uuid
populate_data_path_device: Creating xfs fs on /dev/sdb1
command_check_call: Running command: /sbin/mkfs -t xfs -f -i size=2048 -- /dev/sdb1
meta-data=/dev/sdb1              isize=2048   agcount=4, agsize=61041197 blks
         =                       sectsz=4096  attr=2, projid32bit=1
         =                       crc=1        finobt=1, sparse=0
data     =                       bsize=4096   blocks=244164785, imaxpct=25
         =                       sunit=0      swidth=0 blks
naming   =version 2              bsize=4096   ascii-ci=0 ftype=1
log      =internal log           bsize=4096   blocks=119221, version=2
         =                       sectsz=4096  sunit=1 blks, lazy-count=1
realtime =none                   extsz=4096   blocks=0, rtextents=0
mount: Mounting /dev/sdb1 on /var/lib/ceph/tmp/mnt.c5z_ol with options noatime,inode64
command_check_call: Running command: /bin/mount -t xfs -o noatime,inode64 -- /dev/sdb1 /var/lib/ceph/tmp/mnt.c5z_ol
mount: wrong fs type, bad option, bad superblock on /dev/sdb1,
       missing codepage or helper program, or other error

       In some cases useful info is found in syslog - try
       dmesg | tail or so.
Traceback (most recent call last):
  File "/usr/sbin/ceph-disk", line 9, in <module>
    load_entry_point('ceph-disk==1.0.0', 'console_scripts', 'ceph-disk')()
  File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 5230, in run
    main(sys.argv[1:])
  File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 5181, in main
    args.func(args)
  File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 1874, in main
    Prepare.factory(args).prepare()
  File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 1863, in prepare
    self.prepare_locked()
  File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 1894, in prepare_locked
    self.data.prepare(self.journal)
  File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 2653, in prepare
    self.prepare_device(*to_prepare_list)
  File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 2826, in prepare_device
    self.populate_data_path_device(*to_prepare_list)
  File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 2787, in populate_data_path_device
    options=self.mount_options)
  File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 1337, in mount
    raise MountError(e)
ceph_disk.main.MountError: <exception str() failed>
```

I tried with `docker run --rm -d --privileged=true -v /dev/:/dev/ -e OSD_DEVICE=/dev/sdb ceph/daemon zap_device` but does not make any diff.

When I check `dmesg` I have following error

```
[606872.688903] XFS (dm-12): Mounting V4 Filesystem
[606872.706706] XFS (dm-12): Ending clean mount
[606873.248128] Alternate GPT is invalid, using primary GPT.
[606873.248140]  sdb: sdb1 sdb2
[606873.264243] Alternate GPT is invalid, using primary GPT.
[606873.264250]  sdb: sdb1 sdb2
[606874.358084]  sdb: unknown partition table
[606874.366227]  sdb: unknown partition table
[606875.499393]  sdb:
[606875.897352]  sdb:
[606876.979224]  sdb: sdb2
[606878.146455]  sdb: sdb2
[606879.313983]  sdb: sdb1 sdb2
[606882.241360] XFS (sdb1): Superblock has unknown read-only compatible features (0x1) enabled.
[606882.241861] XFS (sdb1): Attempted to mount read-only compatible filesystem read-write.
Filesystem can only be safely mounted read only.
[606882.241879] XFS (sdb1): SB validate failed with error 22.
 ```

**Comment by leseb** [comment]
Hum, could this be an issue with your disk?

**Comment by kakawait** [comment]
@leseb I will try with `zap` and `dd` (I tried only with `zap`)

I tried with `parted -s /dev/sdb mklabel gpt mkpart primary xfs 0% 100%` and format using `mkfs.xfs /dev/sdb -f` then `mount -t xfs -o noatime,inode64 -- /dev/sdb /mnt/hdd` it works but no success when delegating to `ceph`

---

@leseb I'm a bit newbee about `dd` do you have some full sample command to execute?

**Comment by leseb** [comment]
You can use this command: `dd if=/dev/zero of=<device> bs=1M count=128 oflag=direct`.
Then please try again and let me know if the problem remains or not.

**Comment by kakawait** [comment]
I tried 

```
parted -s /dev/sdb mklabel gpt mkpart primary xfs 0% 100%
docker run --rm -d --privileged=true -v /dev/:/dev/ -e OSD_DEVICE=/dev/sdb ceph/daemon zap_device
dd if=/dev/zero of=/dev/sdb bs=1M count=128 oflag=direct
```

And I'm using this `docker-compose` for running OSD 

`docker-compose up -d`

```
version: '3'
services:
  osd:
    image: ceph/daemon
    restart: always
    network_mode: "host"
    volumes:
      - ./conf/:/etc/ceph
      - ./data:/var/lib/ceph
      - /dev:/dev
    privileged: true
    environment:
      - OSD_FORCE_ZAP=1
      - OSD_DEVICE=/dev/sdb
    command: osd_ceph_disk
```

I have exactly the same error... I think is not directly related to `Ceph` but I think I miss something...

**Comment by leseb** [comment]
Alright, please zap the device again, then run a bash container like this: `docker run -ti --entrypoint=/bin/bash --privileged=true -v /dev/:/dev/ -v /etc/ceph:/etc/ceph -v /var/lib/ceph:/var/lib/ceph ceph/daemon`. Then into the container run `ceph-disk -v prepare /dev/sdb`, let me know how that goes.

**Comment by kakawait** [comment]
Sorry but same error

```
[root@HOSTNAME ~]# docker run --rm -d --privileged=true -v /dev/:/dev/ -e OSD_DEVICE=/dev/sdb ceph/daemon zap_device
[root@HOSTNAME ~]# ll /dev/sdb*
brw-rw---- 1 root disk 8, 16 Feb 28 12:43 /dev/sdb
[root@HOSTNAME ~]# docker run -ti --entrypoint=/bin/bash --privileged=true -v /dev/:/dev/ -v $(pwd)/conf:/etc/ceph -v $(pwd)/data:/var/lib/ceph ceph/daemon
root@c9c4505a503c:/# ceph-disk -v prepare /dev/sdb
```

**Comment by leseb** [comment]
Can you run the following command on the host? `/bin/mount -t xfs -o noatime,inode64 -- /dev/sdb1 /mnt/` assuming `/mnt` is not used obviously, if it is use another location.

If this doesn't fail, try to look at `dmesg` for any selinux or apparmor errors maybe?

**Comment by kakawait** [comment]
```
[root@HOSTNAME ~]# /bin/mount -t xfs -o noatime,inode64 -- /dev/sdb1 /mnt/hdd/
mount: special device /dev/sdb1 does not exist
[root@HOSTNAME ~]# docker run --rm -d --privileged=true -v /dev/:/dev/ -e OSD_DEVICE=/dev/sdb ceph/daemon zap_device
d44af97e968f2124ee2e9ba2b30df82748392873a039662c749d48d710415761
[root@HOSTNAME ~]# docker run -ti --entrypoint=/bin/bash --privileged=true -v /dev/:/dev/ -v $(pwd)/conf:/etc/ceph -v $(pwd)/data:/var/lib/ceph ceph/daemon
root@4ddb17fc863e:/# ceph-disk -v prepare /dev/sdb
# ERROR
root@4ddb17fc863e:/# exit
exit
[root@dell2211dsy ~]# /bin/mount -t xfs -o noatime,inode64 -- /dev/sdb1 /mnt/hdd/
mount: wrong fs type, bad option, bad superblock on /dev/sdb1,
       missing codepage or helper program, or other error

       In some cases useful info is found in syslog - try
       dmesg | tail or so.
```

Fail as expected because I don't think is about `docker` itself...

**Comment by leseb** [comment]
@kakawait Yes this doesn't seem to be a Docker issue, can you run a fscheck on this partition because something must be wrong with this filesystem.

**Comment by kakawait** [comment]
@leseb sorry I didn't find more time to analyze my issue until now. 

I was googling a bit and a find a potential issue related to `mkfs.xfs` version.

http://serverfault.com/questions/746377/want-to-understand-xfs-strangeness

It explains that my error (see previous `dsmeg` logs) is due to mounting a partition created with `mkfs.xfs` version 5 designed for working on kernel `3.16` or greater on system using older kernel.

I don't have any computer around me to confirm following but since partition creations were done inside `ceph-docker` container with its own binaries (I mean `mkfs.xfs`) there is high probability that `mkfs.xfs` used inside container is version `5` or greater. But I'm using this container on Centos `7.1` which is running on kernel `3.10`... 

That probably the reason why the container fail to mount after partition creations. Even more that explain why I can't reproduce the behavior when using same command outside the container (since it will using system binaries).

I checked _ceph_ documentation http://docs.ceph.com/docs/master/start/os-recommendations/ and Centos `7` and kernel `3.10` seems to be part of supported system. Even if it's really old... But I don't have currently the choice.

On stack answer guys said that I can disable some flag to ask `mkfs.xfs` to build version 4 filesystem rather version 5. I will try but what do you think about ? Maybe _ceph_ is relying on that feature.

**Comment by kakawait** [comment]
@leseb I changed my `conf/ceph.conf` to add 

```
[osd]
osd mkfs options xfs = "-m crc=0 -f"
```

It's seems to work but I don't know if it's a good idea 😨

**Comment by leseb** [comment]
This is really weird, I've never seen that issue before, on both containerized and non-containerized deployment.
I'm not a XFS expert so I don't wether this a good or bad idea... :/

**Comment by kakawait** [comment]
close seems I got a workaround
