### ISSUE TITLE
Issue with non-privileged OSDs and SElinux

### ISSUE THREAD

**Issue by leseb** [ceph/ceph-container#521]
Can not mount the OSD fs, `ceph-disk` logs:

```
Feb 28 13:43:27 docker-centos-osd ceph-osd-run.sh[23738]: 2017-02-28 13:43:27  /entrypoint.sh: static: does not generate config
Feb 28 13:43:27 docker-centos-osd ceph-osd-run.sh[23738]: main_activate: path = /dev/sdb1
Feb 28 13:43:27 docker-centos-osd ceph-osd-run.sh[23738]: get_dm_uuid: get_dm_uuid /dev/sdb1 uuid path is /sys/dev/block/8:17/dm/uuid
Feb 28 13:43:27 docker-centos-osd ceph-osd-run.sh[23738]: command: Running command: /sbin/blkid -o udev -p /dev/sdb1
Feb 28 13:43:27 docker-centos-osd ceph-osd-run.sh[23738]: command: Running command: /sbin/blkid -p -s TYPE -o value -- /dev/sdb1
Feb 28 13:43:27 docker-centos-osd ceph-osd-run.sh[23738]: command: Running command: /usr/bin/ceph-conf --cluster=ceph --name=osd. --lookup osd_mount_options_xfs
Feb 28 13:43:27 docker-centos-osd ceph-osd-run.sh[23738]: mount: Mounting /dev/sdb1 on /var/lib/ceph/tmp/mnt.rguqya with options noatime,largeio,inode64,swalloc
Feb 28 13:43:27 docker-centos-osd ceph-osd-run.sh[23738]: command_check_call: Running command: /bin/mount -t xfs -o noatime,largeio,inode64,swalloc -- /dev/sdb1 /var/lib/ceph/tmp/mnt.rguqya
Feb 28 13:43:27 docker-centos-osd ceph-osd-run.sh[23738]: mount: /dev/sdb1 is write-protected, mounting read-only
Feb 28 13:43:27 docker-centos-osd ceph-osd-run.sh[23738]: mount: cannot mount /dev/sdb1 read-only
Feb 28 13:43:27 docker-centos-osd ceph-osd-run.sh[23738]: Traceback (most recent call last):
Feb 28 13:43:27 docker-centos-osd ceph-osd-run.sh[23738]: File "/usr/sbin/ceph-disk", line 9, in <module>
Feb 28 13:43:27 docker-centos-osd ceph-osd-run.sh[23738]: load_entry_point('ceph-disk==1.0.0', 'console_scripts', 'ceph-disk')()
Feb 28 13:43:27 docker-centos-osd ceph-osd-run.sh[23738]: File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 5230, in run
Feb 28 13:43:27 docker-centos-osd ceph-osd-run.sh[23738]: main(sys.argv[1:])
Feb 28 13:43:27 docker-centos-osd ceph-osd-run.sh[23738]: File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 5181, in main
Feb 28 13:43:27 docker-centos-osd ceph-osd-run.sh[23738]: args.func(args)
Feb 28 13:43:27 docker-centos-osd ceph-osd-run.sh[23738]: File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 3532, in main_activate
Feb 28 13:43:27 docker-centos-osd ceph-osd-run.sh[23738]: reactivate=args.reactivate,
Feb 28 13:43:27 docker-centos-osd ceph-osd-run.sh[23738]: File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 3266, in mount_activate
Feb 28 13:43:27 docker-centos-osd ceph-osd-run.sh[23738]: path = mount(dev=dev, fstype=fstype, options=mount_options)
Feb 28 13:43:27 docker-centos-osd ceph-osd-run.sh[23738]: File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 1337, in mount
Feb 28 13:43:27 docker-centos-osd ceph-osd-run.sh[23738]: raise MountError(e)
Feb 28 13:43:27 docker-centos-osd ceph-osd-run.sh[23738]: ceph_disk.main.MountError: <exception str() failed>
```

Selinux logs:

```
time->Tue Feb 28 13:41:45 2017
type=SYSCALL msg=audit(1488289305.045:162836): arch=c000003e syscall=165 success=no exit=-13 a0=ea0240 a1=ea02f0 a2=ea0260 a3=c0ed0400 items=0 ppid=18748 pid=18755 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="mount" exe="/bin/mount" subj=system_u:system_r:svirt_lxc_net_t:s0:c590,c721 key=(null)
type=AVC msg=audit(1488289305.045:162836): avc:  denied  { mount } for  pid=18755 comm="mount" name="/" dev="sdd1" ino=32 scontext=system_u:system_r:svirt_lxc_net_t:s0:c590,c721 tcontext=system_u:object_r:fs_t:s0 tclass=filesystem
```

SElinux:

```
[root@docker-centos-osd ~]# getenforce
Enforcing
```

Setting to permissive solves the issue.

**Comment by leseb** [comment]
Seems to be related to the removal of `--pid=host`...

**Comment by ktdreyer** [comment]
@b-ranto any ideas on this selinux issue?

**Comment by b-ranto** [comment]
It says that mount was called with svirt_lxc_net_t context which suggests containers did not do/define the appropriate context transition when calling mount.

**Comment by sjkyspa** [comment]
any updates about how to fix this?

**Comment by leseb** [comment]
@sjkyspa you can run your container with `--pid=host`. If you run on k8s you're fine.
