### ISSUE TITLE
Centos 7 OSD OSD::mkfs: ObjectStore::mkfs failed with error -13

### ISSUE THREAD

**Issue by grailsweb** [ceph/ceph-container#666]
Hi,

In Centos 7 OS trying to run the osd docker daemon, but its not starting giving below error message.

created my own docker image and starting it.

```
docker run -d --net=host \
--pid=host \
--privileged=true \
-v /etc/ceph:/etc/ceph \
-v /var/lib/ceph/:/var/lib/ceph/ \
-v /dev/:/dev/ \
-e OSD_DEVICE=/dev/sdb \
-e OSD_FORCE_ZAP=1 \
 -e DEBUG=verbose \
mysite osd
```

below is  the debug message any help to resolve this error?

```
Jun 12 08:19:56 webserver dockerd-current: time="2017-06-12T08:19:56.662727772-04:00" level=info msg="{Action=create, Username=root, LoginUID=0, PID=14476}"
Jun 12 08:19:56 webserver kernel: XFS (dm-4): Mounting V5 Filesystem
Jun 12 08:19:56 webserver kernel: XFS (dm-4): Ending clean mount
Jun 12 08:19:56 webserver kernel: XFS (dm-4): Unmounting Filesystem
Jun 12 08:19:56 webserver kernel: XFS (dm-4): Mounting V5 Filesystem
Jun 12 08:19:56 webserver kernel: XFS (dm-4): Ending clean mount
Jun 12 08:19:56 webserver kernel: XFS (dm-4): Unmounting Filesystem
Jun 12 08:19:57 webserver dockerd-current: time="2017-06-12T08:19:57.011376910-04:00" level=info msg="{Action=start, Username=root, LoginUID=0, PID=14476}"
Jun 12 08:19:57 webserver kernel: XFS (dm-4): Mounting V5 Filesystem
Jun 12 08:19:57 webserver kernel: XFS (dm-4): Ending clean mount
Jun 12 08:19:57 webserver systemd: Started docker container 8d5c3ee2149d4d011ff0ab8c1fa9d214292da82f8155bc409268db8b21f4dd2c.
Jun 12 08:19:57 webserver systemd: Starting docker container 8d5c3ee2149d4d011ff0ab8c1fa9d214292da82f8155bc409268db8b21f4dd2c.
Jun 12 08:19:57 webserver oci-register-machine[14549]: 2017/06/12 08:19:57 Register machine: prestart 8d5c3ee2149d4d011ff0ab8c1fa9d214292da82f8155bc409268db8b21f4dd2c 14543 /var/lib/docker/devicemapper/mnt/1ec4cbe008cdb7db66dbdd8eb73b16e4adafcf1f56c3f2570a5441f8ef176e2d/rootfs
Jun 12 08:19:57 webserver systemd-machined: New machine 8d5c3ee2149d4d011ff0ab8c1fa9d214.
Jun 12 08:19:57 webserver journal: + case "$KV_TYPE" in
Jun 12 08:19:57 webserver journal: + source /config.static.sh
Jun 12 08:19:57 webserver journal: ++ set -e
Jun 12 08:19:57 webserver journal: ++ to_lowercase osd
Jun 12 08:19:57 webserver journal: ++ echo osd
Jun 12 08:19:57 webserver journal: + CEPH_DAEMON=osd
Jun 12 08:19:57 webserver journal: + create_mandatory_directories
Jun 12 08:19:57 webserver journal: + for keyring in '$OSD_BOOTSTRAP_KEYRING' '$MDS_BOOTSTRAP_KEYRING' '$RGW_BOOTSTRAP_KEYRING'
Jun 12 08:19:57 webserver journal: ++ dirname /var/lib/ceph/bootstrap-osd/ceph.keyring
Jun 12 08:19:57 webserver journal: VERBOSE: activating bash debugging mode.
Jun 12 08:19:57 webserver journal: + mkdir -p /var/lib/ceph/bootstrap-osd
Jun 12 08:19:57 webserver journal: + for keyring in '$OSD_BOOTSTRAP_KEYRING' '$MDS_BOOTSTRAP_KEYRING' '$RGW_BOOTSTRAP_KEYRING'
Jun 12 08:19:57 webserver journal: ++ dirname /var/lib/ceph/bootstrap-mds/ceph.keyring
Jun 12 08:19:57 webserver journal: + mkdir -p /var/lib/ceph/bootstrap-mds
Jun 12 08:19:57 webserver journal: + for keyring in '$OSD_BOOTSTRAP_KEYRING' '$MDS_BOOTSTRAP_KEYRING' '$RGW_BOOTSTRAP_KEYRING'
Jun 12 08:19:57 webserver journal: ++ dirname /var/lib/ceph/bootstrap-rgw/ceph.keyring
Jun 12 08:19:57 webserver journal: + mkdir -p /var/lib/ceph/bootstrap-rgw
Jun 12 08:19:57 webserver journal: + for directory in mon osd mds radosgw tmp mgr
Jun 12 08:19:57 webserver journal: + mkdir -p /var/lib/ceph/mon
Jun 12 08:19:57 webserver journal: + for directory in mon osd mds radosgw tmp mgr
Jun 12 08:19:57 webserver journal: + mkdir -p /var/lib/ceph/osd
Jun 12 08:19:57 webserver journal: + for directory in mon osd mds radosgw tmp mgr
Jun 12 08:19:57 webserver journal: + mkdir -p /var/lib/ceph/mds
Jun 12 08:19:57 webserver journal: + for directory in mon osd mds radosgw tmp mgr
Jun 12 08:19:57 webserver journal: + mkdir -p /var/lib/ceph/radosgw
Jun 12 08:19:57 webserver journal: + for directory in mon osd mds radosgw tmp mgr
Jun 12 08:19:57 webserver journal: + mkdir -p /var/lib/ceph/tmp
Jun 12 08:19:57 webserver journal: + for directory in mon osd mds radosgw tmp mgr
Jun 12 08:19:57 webserver journal: + mkdir -p /var/lib/ceph/mgr
Jun 12 08:19:57 webserver journal: + mkdir -p /var/lib/ceph/mon/ceph-webserver
Jun 12 08:19:57 webserver journal: + mkdir -p /var/run/ceph
Jun 12 08:19:57 webserver journal: + mkdir -p /var/lib/ceph/radosgw/webserver
Jun 12 08:19:57 webserver journal: + mkdir -p /var/lib/ceph/mds/ceph-mds-webserver
Jun 12 08:19:57 webserver journal: + mkdir -p /var/lib/ceph/mgr/ceph-webserver
Jun 12 08:19:57 webserver journal: + chown -R ceph. /var/run/ceph/ /var/lib/ceph/bootstrap-mds /var/lib/ceph/bootstrap-osd /var/lib/ceph/bootstrap-rgw /var/lib/ceph/mds /var/lib/ceph/mgr /var/lib/ceph/mon /var/lib/ceph/osd /var/lib/ceph/radosgw /var/lib/ceph/tmp
Jun 12 08:19:57 webserver journal: + case "$CEPH_DAEMON" in
Jun 12 08:19:57 webserver journal: + source start_osd.sh
Jun 12 08:19:57 webserver journal: ++ set -e
Jun 12 08:19:57 webserver journal: ++ is_redhat
Jun 12 08:19:57 webserver journal: ++ get_package_manager
Jun 12 08:19:57 webserver journal: ++ is_available rpm
Jun 12 08:19:57 webserver journal: ++ command -v rpm
Jun 12 08:19:57 webserver journal: ++ is_available dpkg
Jun 12 08:19:57 webserver journal: ++ command -v dpkg
Jun 12 08:19:57 webserver journal: ++ OS_VENDOR=ubuntu
Jun 12 08:19:57 webserver journal: ++ [[ ubuntu == \r\e\d\h\a\t ]]
Jun 12 08:19:57 webserver journal: ++ is_ubuntu
Jun 12 08:19:57 webserver journal: ++ get_package_manager
Jun 12 08:19:57 webserver journal: ++ is_available rpm
Jun 12 08:19:57 webserver journal: ++ command -v rpm
Jun 12 08:19:57 webserver journal: ++ is_available dpkg
Jun 12 08:19:57 webserver journal: ++ command -v dpkg
Jun 12 08:19:57 webserver journal: ++ OS_VENDOR=ubuntu
Jun 12 08:19:57 webserver journal: ++ [[ ubuntu == \u\b\u\n\t\u ]]
Jun 12 08:19:57 webserver journal: ++ source /etc/default/ceph
Jun 12 08:19:57 webserver journal: +++ TCMALLOC_MAX_TOTAL_THREAD_CACHE_BYTES=134217728
Jun 12 08:19:57 webserver journal: + start_osd
Jun 12 08:19:57 webserver journal: + get_config
Jun 12 08:19:57 webserver journal: + log 'static: does not generate config'
Jun 12 08:19:57 webserver journal: + '[' -z 'static: does not generate config' ']'
Jun 12 08:19:57 webserver journal: ++ date '+%F %T'
Jun 12 08:19:57 webserver journal: + TIMESTAMP='2017-06-12 12:19:57'
Jun 12 08:19:57 webserver journal: + echo '2017-06-12 12:19:57  /entrypoint.sh: static: does not generate config'
Jun 12 08:19:57 webserver journal: + return 0
Jun 12 08:19:57 webserver journal: + check_config
Jun 12 08:19:57 webserver journal: + [[ ! -e /etc/ceph/ceph.conf ]]
Jun 12 08:19:57 webserver journal: + '[' 0 -eq 1 ']'
Jun 12 08:19:57 webserver journal: + case "$OSD_TYPE" in
Jun 12 08:19:57 webserver journal: + osd_trying_to_determine_scenario
Jun 12 08:19:57 webserver journal: + '[' -z /dev/sdb ']'
Jun 12 08:19:57 webserver journal: ++ parted --script /dev/sdb print
Jun 12 08:19:57 webserver journal: ++ egrep -sq '^ 1.*ceph data'
Jun 12 08:19:57 webserver journal: 2017-06-12 12:19:57  /entrypoint.sh: static: does not generate config
Jun 12 08:19:57 webserver journal: + log 'Bootstrapped OSD found; activating /dev/sdb'
Jun 12 08:19:57 webserver journal: + '[' -z 'Bootstrapped OSD found; activating /dev/sdb' ']'
Jun 12 08:19:57 webserver journal: ++ date '+%F %T'
Jun 12 08:19:57 webserver journal: + TIMESTAMP='2017-06-12 12:19:57'
Jun 12 08:19:57 webserver journal: + echo '2017-06-12 12:19:57  /entrypoint.sh: Bootstrapped OSD found; activating /dev/sdb'
Jun 12 08:19:57 webserver journal: 2017-06-12 12:19:57  /entrypoint.sh: Bootstrapped OSD found; activating /dev/sdb
Jun 12 08:19:57 webserver journal: + return 0
Jun 12 08:19:57 webserver journal: + source osd_disk_activate.sh
Jun 12 08:19:57 webserver journal: ++ set -e
Jun 12 08:19:57 webserver journal: + osd_activate
Jun 12 08:19:57 webserver journal: + [[ -z /dev/sdb ]]
Jun 12 08:19:57 webserver journal: + CEPH_DISK_OPTIONS=
Jun 12 08:19:57 webserver journal: ++ blkid -o value -s PARTUUID /dev/sdb1
Jun 12 08:19:57 webserver journal: + DATA_UUID=e1944784-da89-4fea-91e6-796d054004ad
Jun 12 08:19:57 webserver journal: ++ blkid -o value -s PARTUUID /dev/sdb3
Jun 12 08:19:57 webserver journal: ++ true
Jun 12 08:19:57 webserver journal: + LOCKBOX_UUID=
Jun 12 08:19:57 webserver journal: ++ dev_part /dev/sdb 2
Jun 12 08:19:57 webserver journal: ++ local osd_device=/dev/sdb
Jun 12 08:19:57 webserver journal: ++ local osd_partition=2
Jun 12 08:19:57 webserver journal: ++ [[ -L /dev/sdb ]]
Jun 12 08:19:57 webserver journal: ++ [[ b == [0-9] ]]
Jun 12 08:19:57 webserver journal: ++ echo /dev/sdb2
Jun 12 08:19:57 webserver journal: + JOURNAL_PART=/dev/sdb2
Jun 12 08:19:57 webserver journal: ++ readlink -f /dev/sdb
Jun 12 08:19:57 webserver journal: + ACTUAL_OSD_DEVICE=/dev/sdb
Jun 12 08:19:57 webserver journal: + udevadm settle --timeout=600
Jun 12 08:19:57 webserver journal: + [[ -n '' ]]
Jun 12 08:19:57 webserver journal: ++ dev_part /dev/sdb 1
Jun 12 08:19:57 webserver journal: ++ local osd_device=/dev/sdb
Jun 12 08:19:57 webserver journal: ++ local osd_partition=1
Jun 12 08:19:57 webserver journal: ++ [[ -L /dev/sdb ]]
Jun 12 08:19:57 webserver journal: ++ [[ b == [0-9] ]]
Jun 12 08:19:57 webserver journal: ++ echo /dev/sdb1
Jun 12 08:19:57 webserver journal: + wait_for_file /dev/sdb1
Jun 12 08:19:57 webserver journal: + timeout 10 bash -c 'while [ ! -e /dev/sdb1 ]; do echo '\''Waiting for /dev/sdb1 to show up'\'' && sleep 1 ; done'
Jun 12 08:19:57 webserver journal: + chown ceph. /dev/sdb2
Jun 12 08:19:57 webserver journal: ++ dev_part /dev/sdb 1
Jun 12 08:19:57 webserver journal: ++ local osd_device=/dev/sdb
Jun 12 08:19:57 webserver journal: ++ local osd_partition=1
Jun 12 08:19:57 webserver journal: ++ [[ -L /dev/sdb ]]
Jun 12 08:19:57 webserver journal: ++ [[ b == [0-9] ]]
Jun 12 08:19:57 webserver journal: ++ echo /dev/sdb1
Jun 12 08:19:57 webserver journal: + DATA_PART=/dev/sdb1
Jun 12 08:19:57 webserver journal: + MOUNTED_PART=/dev/sdb1
Jun 12 08:19:57 webserver journal: + [[ 0 -eq 1 ]]
Jun 12 08:19:57 webserver journal: + ceph-disk -v --setuser ceph --setgroup disk activate --no-start-daemon /dev/sdb1
Jun 12 08:19:57 webserver journal: main_activate: path = /dev/sdb1
Jun 12 08:19:57 webserver journal: get_dm_uuid: get_dm_uuid /dev/sdb1 uuid path is /sys/dev/block/8:17/dm/uuid
Jun 12 08:19:57 webserver journal: command: Running command: /sbin/blkid -o udev -p /dev/sdb1
Jun 12 08:19:57 webserver journal: command: Running command: /sbin/blkid -p -s TYPE -o value -- /dev/sdb1
Jun 12 08:19:57 webserver journal: command: Running command: /usr/bin/ceph-conf --cluster=ceph --name=osd. --lookup osd_mount_options_xfs
Jun 12 08:19:58 webserver journal: command: Running command: /usr/bin/ceph-conf --cluster=ceph --name=osd. --lookup osd_fs_mount_options_xfs
Jun 12 08:19:58 webserver journal: mount: Mounting /dev/sdb1 on /var/lib/ceph/tmp/mnt.gMECzY with options noatime,inode64
Jun 12 08:19:58 webserver journal: command_check_call: Running command: /bin/mount -t xfs -o noatime,inode64 -- /dev/sdb1 /var/lib/ceph/tmp/mnt.gMECzY
Jun 12 08:19:58 webserver kernel: XFS (sdb1): Mounting V5 Filesystem
Jun 12 08:19:58 webserver kernel: XFS (sdb1): Ending clean mount
Jun 12 08:19:58 webserver journal: activate: Cluster uuid is 45fb028c-9893-4e79-8c2f-5a075dc978f8
Jun 12 08:19:58 webserver journal: command: Running command: /usr/bin/ceph-osd --cluster=ceph --show-config-value=fsid
Jun 12 08:19:58 webserver journal: activate: Cluster name is ceph
Jun 12 08:19:58 webserver journal: activate: OSD uuid is e1944784-da89-4fea-91e6-796d054004ad
Jun 12 08:19:58 webserver journal: activate: OSD id is 0
Jun 12 08:19:58 webserver journal: activate: Initializing OSD...
Jun 12 08:19:58 webserver journal: command_check_call: Running command: /usr/bin/ceph --cluster ceph --name client.bootstrap-osd --keyring /var/lib/ceph/bootstrap-osd/ceph.keyring mon getmap -o /var/lib/ceph/tmp/mnt.gMECzY/activate.monmap
Jun 12 08:19:58 webserver journal: 2017-06-12 12:19:58.652126 7f0d55763700  0 mon.webserver@0(leader) e2 handle_command mon_command({"prefix": "mon getmap"} v 0) v1
Jun 12 08:19:58 webserver journal: 2017-06-12 12:19:58.652149 7f0d55763700  0 log_channel(audit) log [DBG] : from='client.? 192.168.15.15:0/3297178237' entity='client.bootstrap-osd' cmd=[{"prefix": "mon getmap"}]: dispatch
Jun 12 08:19:58 webserver journal: got monmap epoch 2
Jun 12 08:19:58 webserver journal: command: Running command: /usr/bin/timeout 300 ceph-osd --cluster ceph --mkfs --mkkey -i 0 --monmap /var/lib/ceph/tmp/mnt.gMECzY/activate.monmap --osd-data /var/lib/ceph/tmp/mnt.gMECzY --osd-journal /var/lib/ceph/tmp/mnt.gMECzY/journal --osd-uuid e1944784-da89-4fea-91e6-796d054004ad --keyring /var/lib/ceph/tmp/mnt.gMECzY/keyring --setuser ceph --setgroup disk
Jun 12 08:19:58 webserver journal: mount_activate: Failed to activate
Jun 12 08:19:58 webserver journal: unmount: Unmounting /var/lib/ceph/tmp/mnt.gMECzY
Jun 12 08:19:58 webserver journal: command_check_call: Running command: /bin/umount -- /var/lib/ceph/tmp/mnt.gMECzY
Jun 12 08:19:58 webserver kernel: XFS (sdb1): Unmounting Filesystem
Jun 12 08:19:58 webserver journal: Traceback (most recent call last):
Jun 12 08:19:58 webserver journal:  File "/usr/sbin/ceph-disk", line 9, in <module>
Jun 12 08:19:58 webserver journal:    load_entry_point('ceph-disk==1.0.0', 'console_scripts', 'ceph-disk')()
Jun 12 08:19:58 webserver journal:  File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 5692, in run
Jun 12 08:19:58 webserver journal:    main(sys.argv[1:])
Jun 12 08:19:58 webserver journal:  File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 5643, in main
Jun 12 08:19:58 webserver journal:    args.func(args)
Jun 12 08:19:58 webserver journal:  File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 3734, in main_activate
Jun 12 08:19:58 webserver journal:    reactivate=args.reactivate,
Jun 12 08:19:58 webserver journal:  File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 3491, in mount_activate
Jun 12 08:19:58 webserver journal:    (osd_id, cluster) = activate(path, activate_key_template, init)
Jun 12 08:19:58 webserver journal:  File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 3667, in activate
Jun 12 08:19:58 webserver journal:    keyring=keyring,
Jun 12 08:19:58 webserver journal:  File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 3098, in mkfs
Jun 12 08:19:58 webserver journal:    '--setgroup', get_ceph_group(),
Jun 12 08:19:58 webserver journal:  File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 3045, in ceph_osd_mkfs
Jun 12 08:19:58 webserver journal:    raise Error('%s failed : %s' % (str(arguments), error))
Jun 12 08:19:58 webserver journal: ceph_disk.main.Error: Error: ['ceph-osd', '--cluster', 'ceph', '--mkfs', '--mkkey', '-i', u'0', '--monmap', '/var/lib/ceph/tmp/mnt.gMECzY/activate.monmap', '--osd-data', '/var/lib/ceph/tmp/mnt.gMECzY', '--osd-journal', '/var/lib/ceph/tmp/mnt.gMECzY/journal', '--osd-uuid', u'e1944784-da89-4fea-91e6-796d054004ad', '--keyring', '/var/lib/ceph/tmp/mnt.gMECzY/keyring', '--setuser', 'ceph', '--setgroup', 'disk'] failed : 2017-06-12 12:19:58.768513 7fc3922f4c80 -1 filestore(/var/lib/ceph/tmp/mnt.gMECzY) mkjournal error creating journal on /var/lib/ceph/tmp/mnt.gMECzY/journal: (13) Permission denied
Jun 12 08:19:58 webserver journal: 2017-06-12 12:19:58.768552 7fc3922f4c80 -1 OSD::mkfs: ObjectStore::mkfs failed with error -13
Jun 12 08:19:58 webserver journal: 2017-06-12 12:19:58.768893 7fc3922f4c80 -1 #033[0;31m ** ERROR: error creating empty object store in /var/lib/ceph/tmp/mnt.gMECzY: (13) Permission denied#033[0m
Jun 12 08:19:58 webserver journal: 
Jun 12 08:19:58 webserver systemd-machined: Machine 8d5c3ee2149d4d011ff0ab8c1fa9d214 terminated.
Jun 12 08:19:58 webserver oci-register-machine[14693]: 2017/06/12 08:19:58 Register machine: poststop 8d5c3ee2149d4d011ff0ab8c1fa9d214292da82f8155bc409268db8b21f4dd2c 0 /var/lib/docker/devicemapper/mnt/1ec4cbe008cdb7db66dbdd8eb73b16e4adafcf1f56c3f2570a5441f8ef176e2d/rootfs
Jun 12 08:19:59 webserver kernel: XFS (dm-4): Unmounting Filesystem

```

Thanks
SR

**Comment by leseb** [comment]
selinux error?

**Comment by ctriple** [comment]
+1
