### ISSUE TITLE
rgw failed to initialize without more info

### ISSUE THREAD

**Issue by tjamet** [ceph/ceph-container#864]
Hi,

I am trying to start a ceph cluster, currently on a docker for mac host.
I followed the [youtube](https://www.youtube.com/watch?v=FUSTjTBA8f8) video on how to do so but had to tweak some values for my use case.

As docker for mac uses an ext4 backend, I tried either to add the [discouraged configuration](http://docs.ceph.com/docs/jewel/rados/configuration/filesystem-recommendations/) together with the directory mode or to create a virtual drive using `xfs_mkfile -n ${OSD_DEVICE_CREATE_SIZE} ${OSD_DEVICE}`  together with the disk mode.

The discouraged options leads me to rgw start timeout:
```
2017-12-17 00:15:44  /entrypoint.sh: static: does not generate config
HEALTH_WARN no active mgr; Reduced data availability: 24 pgs inactive; Degraded data redundancy: 24 pgs unclean, 24 pgs degraded, 24 pgs undersized; too few PGs per OSD (24 < min 30)
2017-12-17 00:15:45  /entrypoint.sh: SUCCESS
2017-12-17 00:15:45.153184 7f1dc23b7e80  0 deferred set uid:gid to 64045:64045 (ceph:ceph)
2017-12-17 00:15:45.153322 7f1dc23b7e80  0 ceph version 12.2.1 (3e7492b9ada8bdc9a5cd0feafd42fbca27f9c38e) luminous (stable), process (unknown), pid 1
2017-12-17 00:20:45.153490 7f1db04a5700 -1 Initialization timeout, failed to initialize
```

and the mkfs variant ends up with an error as the device is not a full block device:
```
2017-12-17 13:40:10  /entrypoint.sh: static: does not generate config
2017-12-17 13:40:10  /entrypoint.sh: Device detected, assuming ceph-disk scenario is desired
2017-12-17 13:40:10  /entrypoint.sh: Preparing and activating /var/run/ceph/osd_disk
HEALTH_ERR no osds
2017-12-17 13:40:10  /entrypoint.sh: It looks like /var/run/ceph/osd_disk isn't consistent, however OSD_FORCE_ZAP is enabled so we are zapping the device anyway
Traceback (most recent call last):
  File "/usr/sbin/ceph-disk", line 9, in <module>
    load_entry_point('ceph-disk==1.0.0', 'console_scripts', 'ceph-disk')()
  File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 5371, in run
    main(sys.argv[1:])
  File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 5322, in main
    args.func(args)
  File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 4405, in main_zap
    zap(dev)
  File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 1524, in zap
    raise Error('not full block device; cannot zap', dev)
ceph_disk.main.Error: Error: not full block device; cannot zap: /run/ceph/osd_disk
```

Is there a way to run a rgw on a host running ext4 file backends?

Here is the `docker-compose.yml` file I used:

```
version: "3.2"
services:
    mon:
        image: ceph/daemon
        command: mon
        environment:
            - MON_IP=192.168.99.254
            - CEPH_PUBLIC_NETWORK=192.168.99.254/24
        volumes:
            - config:/etc/ceph
            - lib:/var/lib/ceph
        hostname: ceph
        networks:
            default:
                ipv4_address: 192.168.99.254
    mds:
        image: ceph/daemon
        hostname: ceph
        command: mds
        volumes:
            - config:/etc/ceph
            - lib:/var/lib/ceph
        depends_on:
            - mgr
        environment:
            - CEPHFS_CREATE=1
    mgr:
        hostname: ceph
        image: ceph/daemon
        command: mgr
        depends_on:
            - mon
        volumes:
            - config:/etc/ceph
            - lib:/var/lib/ceph
    osd:
        hostname: ceph
        image: ceph/daemon
        command: osd
        depends_on:
            - mgr
        volumes:
            - config:/etc/ceph
            - lib:/var/lib/ceph
    rgw:
        hostname: ceph
        image: ceph/daemon
        command: rgw
        ports:
            - 8080
        volumes:
            - config:/etc/ceph
            - lib:/var/lib/ceph
networks:
    default:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 192.168.99.0/24
volumes:
    config:
    lib:
```

**Comment by leseb** [comment]
Are you looking at deploying a full cluster or just play with it? If you just want to play you should use the `demo` scenario which embeds all the Ceph daemons inside one container.

**Comment by tjamet** [comment]
The purpose is to deploy in the end a full cluster

**Comment by leseb** [comment]
Well, there is not much we can do about the ext4 limitation so you should try differently.  We have a workaround for ext4 but it might not be working on Luminous. ext4 is not supported nor encouraged on Ceph anymore.
Closing this, feel free to re-open if you have other concerns, thanks.
