### ISSUE TITLE
With ceph/demo，I couldn't use S3 java-sdk putObject...

### ISSUE THREAD

**Issue by nanquanyuhao** [ceph/ceph-container#898]
Today,I run the demo use image `ceph/demo:latest` on a physical machine(CentOS 7)  with command `docker run -d --net=host -v /etc/ceph:/etc/ceph -e MON_IP=192.168.41.79 -e CEPH_PUBLIC_NETWORK=192.168.41.0/24 ceph/demo`, everything is okay，and I can access the address http://ip:8080/...

But when I use S3 java-sdk 
```
...
conn.putObject(bucket.getName(), "hello.txt", input, new ObjectMetadata());
...
```
it's warning
```
F:\Java\jdk1.8.0_111\bin\java -javaagent:F:\idea\ideaIU-2017.1.4.win\lib\idea_rt.jar=55624:F:\idea\ideaIU-2017.1.4.win\bin -Dfile.encoding=UTF-8 -classpath F:\Java\jdk1.8.0_111\jre\lib\charsets.jar;F:\Java\jdk1.8.0_111\jre\lib\deploy.jar;F:\Java\jdk1.8.0_111\jre\lib\ext\access-bridge-64.jar;F:\Java\jdk1.8.0_111\jre\lib\ext\cldrdata.jar;F:\Java\jdk1.8.0_111\jre\lib\ext\dnsns.jar;F:\Java\jdk1.8.0_111\jre\lib\ext\jaccess.jar;F:\Java\jdk1.8.0_111\jre\lib\ext\jfxrt.jar;F:\Java\jdk1.8.0_111\jre\lib\ext\localedata.jar;F:\Java\jdk1.8.0_111\jre\lib\ext\nashorn.jar;F:\Java\jdk1.8.0_111\jre\lib\ext\sunec.jar;F:\Java\jdk1.8.0_111\jre\lib\ext\sunjce_provider.jar;F:\Java\jdk1.8.0_111\jre\lib\ext\sunmscapi.jar;F:\Java\jdk1.8.0_111\jre\lib\ext\sunpkcs11.jar;F:\Java\jdk1.8.0_111\jre\lib\ext\zipfs.jar;F:\Java\jdk1.8.0_111\jre\lib\javaws.jar;F:\Java\jdk1.8.0_111\jre\lib\jce.jar;F:\Java\jdk1.8.0_111\jre\lib\jfr.jar;F:\Java\jdk1.8.0_111\jre\lib\jfxswt.jar;F:\Java\jdk1.8.0_111\jre\lib\jsse.jar;F:\Java\jdk1.8.0_111\jre\lib\management-agent.jar;F:\Java\jdk1.8.0_111\jre\lib\plugin.jar;F:\Java\jdk1.8.0_111\jre\lib\resources.jar;F:\Java\jdk1.8.0_111\jre\lib\rt.jar;F:\idea\ideaIU-2017.1.4.win\IdeaProjects\bzone\cephoss\target\classes;F:\maven\localRepository\repo\com\amazonaws\aws-java-sdk-s3\1.11.255\aws-java-sdk-s3-1.11.255.jar;F:\maven\localRepository\repo\com\amazonaws\aws-java-sdk-kms\1.11.255\aws-java-sdk-kms-1.11.255.jar;F:\maven\localRepository\repo\com\amazonaws\aws-java-sdk-core\1.11.255\aws-java-sdk-core-1.11.255.jar;F:\maven\localRepository\repo\commons-logging\commons-logging\1.1.3\commons-logging-1.1.3.jar;F:\maven\localRepository\repo\org\apache\httpcomponents\httpclient\4.5.2\httpclient-4.5.2.jar;F:\maven\localRepository\repo\org\apache\httpcomponents\httpcore\4.4.4\httpcore-4.4.4.jar;F:\maven\localRepository\repo\commons-codec\commons-codec\1.9\commons-codec-1.9.jar;F:\maven\localRepository\repo\software\amazon\ion\ion-java\1.0.2\ion-java-1.0.2.jar;F:\maven\localRepository\repo\com\fasterxml\jackson\core\jackson-databind\2.6.7.1\jackson-databind-2.6.7.1.jar;F:\maven\localRepository\repo\com\fasterxml\jackson\core\jackson-annotations\2.6.0\jackson-annotations-2.6.0.jar;F:\maven\localRepository\repo\com\fasterxml\jackson\core\jackson-core\2.6.7\jackson-core-2.6.7.jar;F:\maven\localRepository\repo\com\fasterxml\jackson\dataformat\jackson-dataformat-cbor\2.6.7\jackson-dataformat-cbor-2.6.7.jar;F:\maven\localRepository\repo\joda-time\joda-time\2.8.1\joda-time-2.8.1.jar;F:\maven\localRepository\repo\com\amazonaws\jmespath-java\1.11.255\jmespath-java-1.11.255.jar net.nanquanyuhao.S3Client
my-new-bucket	2018-02-08T07:50:05.963Z
二月 08, 2018 4:15:44 下午 com.amazonaws.services.s3.AmazonS3Client putObject
警告: No content length specified for stream data.  Stream contents will be buffered in memory and could result in out of memory errors.
Exception in thread "main" com.amazonaws.SdkClientException: Unable to execute HTTP request: Read timed out
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1114)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1064)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4325)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4272)
	at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1749)
	at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1611)
	at net.nanquanyuhao.S3Client.main(S3Client.java:53)
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:170)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:139)
	at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:155)
	at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:284)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:140)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:261)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:165)
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:167)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:272)
	at com.amazonaws.http.protocol.SdkHttpRequestExecutor.doReceiveResponse(SdkHttpRequestExecutor.java:82)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:124)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:271)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
	at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1236)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1056)
	... 11 more

Process finished with exit code 1
```

Could you help me?

**Comment by nanquanyuhao** [comment]
I have solved this problem.
The reason is that the images ceph/demo:latest has the problem, i have change to ceph/demo:tag-build-stable-2.2.11-jewel-centos-7 is OK.
